// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
	"github.com/zhoumingjun/bookmgr/backend/ent/bookfavorite"
)

// BookFavorite is the model entity for the BookFavorite schema.
type BookFavorite struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// UserID holds the value of the "user_id" field.
	UserID uuid.UUID `json:"user_id,omitempty"`
	// BookID holds the value of the "book_id" field.
	BookID uuid.UUID `json:"book_id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the BookFavoriteQuery when eager-loading is set.
	Edges        BookFavoriteEdges `json:"edges"`
	selectValues sql.SelectValues
}

// BookFavoriteEdges holds the relations/edges for other nodes in the graph.
type BookFavoriteEdges struct {
	// User holds the value of the user edge.
	User []*User `json:"user,omitempty"`
	// Book holds the value of the book edge.
	Book []*Book `json:"book,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// UserOrErr returns the User value or an error if the edge
// was not loaded in eager-loading.
func (e BookFavoriteEdges) UserOrErr() ([]*User, error) {
	if e.loadedTypes[0] {
		return e.User, nil
	}
	return nil, &NotLoadedError{edge: "user"}
}

// BookOrErr returns the Book value or an error if the edge
// was not loaded in eager-loading.
func (e BookFavoriteEdges) BookOrErr() ([]*Book, error) {
	if e.loadedTypes[1] {
		return e.Book, nil
	}
	return nil, &NotLoadedError{edge: "book"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*BookFavorite) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case bookfavorite.FieldCreatedAt:
			values[i] = new(sql.NullTime)
		case bookfavorite.FieldID, bookfavorite.FieldUserID, bookfavorite.FieldBookID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the BookFavorite fields.
func (_m *BookFavorite) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case bookfavorite.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case bookfavorite.FieldUserID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field user_id", values[i])
			} else if value != nil {
				_m.UserID = *value
			}
		case bookfavorite.FieldBookID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field book_id", values[i])
			} else if value != nil {
				_m.BookID = *value
			}
		case bookfavorite.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the BookFavorite.
// This includes values selected through modifiers, order, etc.
func (_m *BookFavorite) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryUser queries the "user" edge of the BookFavorite entity.
func (_m *BookFavorite) QueryUser() *UserQuery {
	return NewBookFavoriteClient(_m.config).QueryUser(_m)
}

// QueryBook queries the "book" edge of the BookFavorite entity.
func (_m *BookFavorite) QueryBook() *BookQuery {
	return NewBookFavoriteClient(_m.config).QueryBook(_m)
}

// Update returns a builder for updating this BookFavorite.
// Note that you need to call BookFavorite.Unwrap() before calling this method if this BookFavorite
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *BookFavorite) Update() *BookFavoriteUpdateOne {
	return NewBookFavoriteClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the BookFavorite entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *BookFavorite) Unwrap() *BookFavorite {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: BookFavorite is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *BookFavorite) String() string {
	var builder strings.Builder
	builder.WriteString("BookFavorite(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("user_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.UserID))
	builder.WriteString(", ")
	builder.WriteString("book_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.BookID))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// BookFavorites is a parsable slice of BookFavorite.
type BookFavorites []*BookFavorite
