// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/zhoumingjun/bookmgr/backend/ent/book"
	"github.com/zhoumingjun/bookmgr/backend/ent/bookreadingprogress"
	"github.com/zhoumingjun/bookmgr/backend/ent/user"
)

// BookReadingProgressCreate is the builder for creating a BookReadingProgress entity.
type BookReadingProgressCreate struct {
	config
	mutation *BookReadingProgressMutation
	hooks    []Hook
}

// SetBookID sets the "book_id" field.
func (_c *BookReadingProgressCreate) SetBookID(v uuid.UUID) *BookReadingProgressCreate {
	_c.mutation.SetBookID(v)
	return _c
}

// SetUserID sets the "user_id" field.
func (_c *BookReadingProgressCreate) SetUserID(v uuid.UUID) *BookReadingProgressCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetProgressPercent sets the "progress_percent" field.
func (_c *BookReadingProgressCreate) SetProgressPercent(v int) *BookReadingProgressCreate {
	_c.mutation.SetProgressPercent(v)
	return _c
}

// SetNillableProgressPercent sets the "progress_percent" field if the given value is not nil.
func (_c *BookReadingProgressCreate) SetNillableProgressPercent(v *int) *BookReadingProgressCreate {
	if v != nil {
		_c.SetProgressPercent(*v)
	}
	return _c
}

// SetLastPage sets the "last_page" field.
func (_c *BookReadingProgressCreate) SetLastPage(v int) *BookReadingProgressCreate {
	_c.mutation.SetLastPage(v)
	return _c
}

// SetNillableLastPage sets the "last_page" field if the given value is not nil.
func (_c *BookReadingProgressCreate) SetNillableLastPage(v *int) *BookReadingProgressCreate {
	if v != nil {
		_c.SetLastPage(*v)
	}
	return _c
}

// SetLastReadAt sets the "last_read_at" field.
func (_c *BookReadingProgressCreate) SetLastReadAt(v time.Time) *BookReadingProgressCreate {
	_c.mutation.SetLastReadAt(v)
	return _c
}

// SetNillableLastReadAt sets the "last_read_at" field if the given value is not nil.
func (_c *BookReadingProgressCreate) SetNillableLastReadAt(v *time.Time) *BookReadingProgressCreate {
	if v != nil {
		_c.SetLastReadAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *BookReadingProgressCreate) SetID(v uuid.UUID) *BookReadingProgressCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *BookReadingProgressCreate) SetNillableID(v *uuid.UUID) *BookReadingProgressCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// AddBookIDs adds the "book" edge to the Book entity by IDs.
func (_c *BookReadingProgressCreate) AddBookIDs(ids ...uuid.UUID) *BookReadingProgressCreate {
	_c.mutation.AddBookIDs(ids...)
	return _c
}

// AddBook adds the "book" edges to the Book entity.
func (_c *BookReadingProgressCreate) AddBook(v ...*Book) *BookReadingProgressCreate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddBookIDs(ids...)
}

// AddUserIDs adds the "user" edge to the User entity by IDs.
func (_c *BookReadingProgressCreate) AddUserIDs(ids ...uuid.UUID) *BookReadingProgressCreate {
	_c.mutation.AddUserIDs(ids...)
	return _c
}

// AddUser adds the "user" edges to the User entity.
func (_c *BookReadingProgressCreate) AddUser(v ...*User) *BookReadingProgressCreate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddUserIDs(ids...)
}

// Mutation returns the BookReadingProgressMutation object of the builder.
func (_c *BookReadingProgressCreate) Mutation() *BookReadingProgressMutation {
	return _c.mutation
}

// Save creates the BookReadingProgress in the database.
func (_c *BookReadingProgressCreate) Save(ctx context.Context) (*BookReadingProgress, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *BookReadingProgressCreate) SaveX(ctx context.Context) *BookReadingProgress {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *BookReadingProgressCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *BookReadingProgressCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *BookReadingProgressCreate) defaults() {
	if _, ok := _c.mutation.ProgressPercent(); !ok {
		v := bookreadingprogress.DefaultProgressPercent
		_c.mutation.SetProgressPercent(v)
	}
	if _, ok := _c.mutation.LastPage(); !ok {
		v := bookreadingprogress.DefaultLastPage
		_c.mutation.SetLastPage(v)
	}
	if _, ok := _c.mutation.LastReadAt(); !ok {
		v := bookreadingprogress.DefaultLastReadAt()
		_c.mutation.SetLastReadAt(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := bookreadingprogress.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *BookReadingProgressCreate) check() error {
	if _, ok := _c.mutation.BookID(); !ok {
		return &ValidationError{Name: "book_id", err: errors.New(`ent: missing required field "BookReadingProgress.book_id"`)}
	}
	if _, ok := _c.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "BookReadingProgress.user_id"`)}
	}
	if _, ok := _c.mutation.ProgressPercent(); !ok {
		return &ValidationError{Name: "progress_percent", err: errors.New(`ent: missing required field "BookReadingProgress.progress_percent"`)}
	}
	if v, ok := _c.mutation.ProgressPercent(); ok {
		if err := bookreadingprogress.ProgressPercentValidator(v); err != nil {
			return &ValidationError{Name: "progress_percent", err: fmt.Errorf(`ent: validator failed for field "BookReadingProgress.progress_percent": %w`, err)}
		}
	}
	if _, ok := _c.mutation.LastPage(); !ok {
		return &ValidationError{Name: "last_page", err: errors.New(`ent: missing required field "BookReadingProgress.last_page"`)}
	}
	if v, ok := _c.mutation.LastPage(); ok {
		if err := bookreadingprogress.LastPageValidator(v); err != nil {
			return &ValidationError{Name: "last_page", err: fmt.Errorf(`ent: validator failed for field "BookReadingProgress.last_page": %w`, err)}
		}
	}
	if _, ok := _c.mutation.LastReadAt(); !ok {
		return &ValidationError{Name: "last_read_at", err: errors.New(`ent: missing required field "BookReadingProgress.last_read_at"`)}
	}
	return nil
}

func (_c *BookReadingProgressCreate) sqlSave(ctx context.Context) (*BookReadingProgress, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *BookReadingProgressCreate) createSpec() (*BookReadingProgress, *sqlgraph.CreateSpec) {
	var (
		_node = &BookReadingProgress{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(bookreadingprogress.Table, sqlgraph.NewFieldSpec(bookreadingprogress.FieldID, field.TypeUUID))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.BookID(); ok {
		_spec.SetField(bookreadingprogress.FieldBookID, field.TypeUUID, value)
		_node.BookID = value
	}
	if value, ok := _c.mutation.UserID(); ok {
		_spec.SetField(bookreadingprogress.FieldUserID, field.TypeUUID, value)
		_node.UserID = value
	}
	if value, ok := _c.mutation.ProgressPercent(); ok {
		_spec.SetField(bookreadingprogress.FieldProgressPercent, field.TypeInt, value)
		_node.ProgressPercent = value
	}
	if value, ok := _c.mutation.LastPage(); ok {
		_spec.SetField(bookreadingprogress.FieldLastPage, field.TypeInt, value)
		_node.LastPage = value
	}
	if value, ok := _c.mutation.LastReadAt(); ok {
		_spec.SetField(bookreadingprogress.FieldLastReadAt, field.TypeTime, value)
		_node.LastReadAt = value
	}
	if nodes := _c.mutation.BookIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   bookreadingprogress.BookTable,
			Columns: bookreadingprogress.BookPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(book.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   bookreadingprogress.UserTable,
			Columns: bookreadingprogress.UserPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// BookReadingProgressCreateBulk is the builder for creating many BookReadingProgress entities in bulk.
type BookReadingProgressCreateBulk struct {
	config
	err      error
	builders []*BookReadingProgressCreate
}

// Save creates the BookReadingProgress entities in the database.
func (_c *BookReadingProgressCreateBulk) Save(ctx context.Context) ([]*BookReadingProgress, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*BookReadingProgress, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*BookReadingProgressMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *BookReadingProgressCreateBulk) SaveX(ctx context.Context) []*BookReadingProgress {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *BookReadingProgressCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *BookReadingProgressCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
