// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/zhoumingjun/bookmgr/backend/ent/book"
	"github.com/zhoumingjun/bookmgr/backend/ent/bookreview"
	"github.com/zhoumingjun/bookmgr/backend/ent/predicate"
	"github.com/zhoumingjun/bookmgr/backend/ent/user"
)

// BookReviewUpdate is the builder for updating BookReview entities.
type BookReviewUpdate struct {
	config
	hooks    []Hook
	mutation *BookReviewMutation
}

// Where appends a list predicates to the BookReviewUpdate builder.
func (_u *BookReviewUpdate) Where(ps ...predicate.BookReview) *BookReviewUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetBookID sets the "book_id" field.
func (_u *BookReviewUpdate) SetBookID(v uuid.UUID) *BookReviewUpdate {
	_u.mutation.SetBookID(v)
	return _u
}

// SetNillableBookID sets the "book_id" field if the given value is not nil.
func (_u *BookReviewUpdate) SetNillableBookID(v *uuid.UUID) *BookReviewUpdate {
	if v != nil {
		_u.SetBookID(*v)
	}
	return _u
}

// SetReviewerID sets the "reviewer_id" field.
func (_u *BookReviewUpdate) SetReviewerID(v uuid.UUID) *BookReviewUpdate {
	_u.mutation.SetReviewerID(v)
	return _u
}

// SetNillableReviewerID sets the "reviewer_id" field if the given value is not nil.
func (_u *BookReviewUpdate) SetNillableReviewerID(v *uuid.UUID) *BookReviewUpdate {
	if v != nil {
		_u.SetReviewerID(*v)
	}
	return _u
}

// SetAction sets the "action" field.
func (_u *BookReviewUpdate) SetAction(v string) *BookReviewUpdate {
	_u.mutation.SetAction(v)
	return _u
}

// SetNillableAction sets the "action" field if the given value is not nil.
func (_u *BookReviewUpdate) SetNillableAction(v *string) *BookReviewUpdate {
	if v != nil {
		_u.SetAction(*v)
	}
	return _u
}

// SetStatusFrom sets the "status_from" field.
func (_u *BookReviewUpdate) SetStatusFrom(v string) *BookReviewUpdate {
	_u.mutation.SetStatusFrom(v)
	return _u
}

// SetNillableStatusFrom sets the "status_from" field if the given value is not nil.
func (_u *BookReviewUpdate) SetNillableStatusFrom(v *string) *BookReviewUpdate {
	if v != nil {
		_u.SetStatusFrom(*v)
	}
	return _u
}

// SetStatusTo sets the "status_to" field.
func (_u *BookReviewUpdate) SetStatusTo(v string) *BookReviewUpdate {
	_u.mutation.SetStatusTo(v)
	return _u
}

// SetNillableStatusTo sets the "status_to" field if the given value is not nil.
func (_u *BookReviewUpdate) SetNillableStatusTo(v *string) *BookReviewUpdate {
	if v != nil {
		_u.SetStatusTo(*v)
	}
	return _u
}

// SetReason sets the "reason" field.
func (_u *BookReviewUpdate) SetReason(v string) *BookReviewUpdate {
	_u.mutation.SetReason(v)
	return _u
}

// SetNillableReason sets the "reason" field if the given value is not nil.
func (_u *BookReviewUpdate) SetNillableReason(v *string) *BookReviewUpdate {
	if v != nil {
		_u.SetReason(*v)
	}
	return _u
}

// ClearReason clears the value of the "reason" field.
func (_u *BookReviewUpdate) ClearReason() *BookReviewUpdate {
	_u.mutation.ClearReason()
	return _u
}

// AddBookIDs adds the "book" edge to the Book entity by IDs.
func (_u *BookReviewUpdate) AddBookIDs(ids ...uuid.UUID) *BookReviewUpdate {
	_u.mutation.AddBookIDs(ids...)
	return _u
}

// AddBook adds the "book" edges to the Book entity.
func (_u *BookReviewUpdate) AddBook(v ...*Book) *BookReviewUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddBookIDs(ids...)
}

// AddReviewerIDs adds the "reviewer" edge to the User entity by IDs.
func (_u *BookReviewUpdate) AddReviewerIDs(ids ...uuid.UUID) *BookReviewUpdate {
	_u.mutation.AddReviewerIDs(ids...)
	return _u
}

// AddReviewer adds the "reviewer" edges to the User entity.
func (_u *BookReviewUpdate) AddReviewer(v ...*User) *BookReviewUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddReviewerIDs(ids...)
}

// Mutation returns the BookReviewMutation object of the builder.
func (_u *BookReviewUpdate) Mutation() *BookReviewMutation {
	return _u.mutation
}

// ClearBook clears all "book" edges to the Book entity.
func (_u *BookReviewUpdate) ClearBook() *BookReviewUpdate {
	_u.mutation.ClearBook()
	return _u
}

// RemoveBookIDs removes the "book" edge to Book entities by IDs.
func (_u *BookReviewUpdate) RemoveBookIDs(ids ...uuid.UUID) *BookReviewUpdate {
	_u.mutation.RemoveBookIDs(ids...)
	return _u
}

// RemoveBook removes "book" edges to Book entities.
func (_u *BookReviewUpdate) RemoveBook(v ...*Book) *BookReviewUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveBookIDs(ids...)
}

// ClearReviewer clears all "reviewer" edges to the User entity.
func (_u *BookReviewUpdate) ClearReviewer() *BookReviewUpdate {
	_u.mutation.ClearReviewer()
	return _u
}

// RemoveReviewerIDs removes the "reviewer" edge to User entities by IDs.
func (_u *BookReviewUpdate) RemoveReviewerIDs(ids ...uuid.UUID) *BookReviewUpdate {
	_u.mutation.RemoveReviewerIDs(ids...)
	return _u
}

// RemoveReviewer removes "reviewer" edges to User entities.
func (_u *BookReviewUpdate) RemoveReviewer(v ...*User) *BookReviewUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveReviewerIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *BookReviewUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *BookReviewUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *BookReviewUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *BookReviewUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *BookReviewUpdate) check() error {
	if v, ok := _u.mutation.Action(); ok {
		if err := bookreview.ActionValidator(v); err != nil {
			return &ValidationError{Name: "action", err: fmt.Errorf(`ent: validator failed for field "BookReview.action": %w`, err)}
		}
	}
	if v, ok := _u.mutation.StatusFrom(); ok {
		if err := bookreview.StatusFromValidator(v); err != nil {
			return &ValidationError{Name: "status_from", err: fmt.Errorf(`ent: validator failed for field "BookReview.status_from": %w`, err)}
		}
	}
	if v, ok := _u.mutation.StatusTo(); ok {
		if err := bookreview.StatusToValidator(v); err != nil {
			return &ValidationError{Name: "status_to", err: fmt.Errorf(`ent: validator failed for field "BookReview.status_to": %w`, err)}
		}
	}
	return nil
}

func (_u *BookReviewUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(bookreview.Table, bookreview.Columns, sqlgraph.NewFieldSpec(bookreview.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.BookID(); ok {
		_spec.SetField(bookreview.FieldBookID, field.TypeUUID, value)
	}
	if value, ok := _u.mutation.ReviewerID(); ok {
		_spec.SetField(bookreview.FieldReviewerID, field.TypeUUID, value)
	}
	if value, ok := _u.mutation.Action(); ok {
		_spec.SetField(bookreview.FieldAction, field.TypeString, value)
	}
	if value, ok := _u.mutation.StatusFrom(); ok {
		_spec.SetField(bookreview.FieldStatusFrom, field.TypeString, value)
	}
	if value, ok := _u.mutation.StatusTo(); ok {
		_spec.SetField(bookreview.FieldStatusTo, field.TypeString, value)
	}
	if value, ok := _u.mutation.Reason(); ok {
		_spec.SetField(bookreview.FieldReason, field.TypeString, value)
	}
	if _u.mutation.ReasonCleared() {
		_spec.ClearField(bookreview.FieldReason, field.TypeString)
	}
	if _u.mutation.BookCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   bookreview.BookTable,
			Columns: []string{bookreview.BookColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(book.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedBookIDs(); len(nodes) > 0 && !_u.mutation.BookCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   bookreview.BookTable,
			Columns: []string{bookreview.BookColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(book.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.BookIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   bookreview.BookTable,
			Columns: []string{bookreview.BookColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(book.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ReviewerCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   bookreview.ReviewerTable,
			Columns: []string{bookreview.ReviewerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedReviewerIDs(); len(nodes) > 0 && !_u.mutation.ReviewerCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   bookreview.ReviewerTable,
			Columns: []string{bookreview.ReviewerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ReviewerIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   bookreview.ReviewerTable,
			Columns: []string{bookreview.ReviewerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{bookreview.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// BookReviewUpdateOne is the builder for updating a single BookReview entity.
type BookReviewUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *BookReviewMutation
}

// SetBookID sets the "book_id" field.
func (_u *BookReviewUpdateOne) SetBookID(v uuid.UUID) *BookReviewUpdateOne {
	_u.mutation.SetBookID(v)
	return _u
}

// SetNillableBookID sets the "book_id" field if the given value is not nil.
func (_u *BookReviewUpdateOne) SetNillableBookID(v *uuid.UUID) *BookReviewUpdateOne {
	if v != nil {
		_u.SetBookID(*v)
	}
	return _u
}

// SetReviewerID sets the "reviewer_id" field.
func (_u *BookReviewUpdateOne) SetReviewerID(v uuid.UUID) *BookReviewUpdateOne {
	_u.mutation.SetReviewerID(v)
	return _u
}

// SetNillableReviewerID sets the "reviewer_id" field if the given value is not nil.
func (_u *BookReviewUpdateOne) SetNillableReviewerID(v *uuid.UUID) *BookReviewUpdateOne {
	if v != nil {
		_u.SetReviewerID(*v)
	}
	return _u
}

// SetAction sets the "action" field.
func (_u *BookReviewUpdateOne) SetAction(v string) *BookReviewUpdateOne {
	_u.mutation.SetAction(v)
	return _u
}

// SetNillableAction sets the "action" field if the given value is not nil.
func (_u *BookReviewUpdateOne) SetNillableAction(v *string) *BookReviewUpdateOne {
	if v != nil {
		_u.SetAction(*v)
	}
	return _u
}

// SetStatusFrom sets the "status_from" field.
func (_u *BookReviewUpdateOne) SetStatusFrom(v string) *BookReviewUpdateOne {
	_u.mutation.SetStatusFrom(v)
	return _u
}

// SetNillableStatusFrom sets the "status_from" field if the given value is not nil.
func (_u *BookReviewUpdateOne) SetNillableStatusFrom(v *string) *BookReviewUpdateOne {
	if v != nil {
		_u.SetStatusFrom(*v)
	}
	return _u
}

// SetStatusTo sets the "status_to" field.
func (_u *BookReviewUpdateOne) SetStatusTo(v string) *BookReviewUpdateOne {
	_u.mutation.SetStatusTo(v)
	return _u
}

// SetNillableStatusTo sets the "status_to" field if the given value is not nil.
func (_u *BookReviewUpdateOne) SetNillableStatusTo(v *string) *BookReviewUpdateOne {
	if v != nil {
		_u.SetStatusTo(*v)
	}
	return _u
}

// SetReason sets the "reason" field.
func (_u *BookReviewUpdateOne) SetReason(v string) *BookReviewUpdateOne {
	_u.mutation.SetReason(v)
	return _u
}

// SetNillableReason sets the "reason" field if the given value is not nil.
func (_u *BookReviewUpdateOne) SetNillableReason(v *string) *BookReviewUpdateOne {
	if v != nil {
		_u.SetReason(*v)
	}
	return _u
}

// ClearReason clears the value of the "reason" field.
func (_u *BookReviewUpdateOne) ClearReason() *BookReviewUpdateOne {
	_u.mutation.ClearReason()
	return _u
}

// AddBookIDs adds the "book" edge to the Book entity by IDs.
func (_u *BookReviewUpdateOne) AddBookIDs(ids ...uuid.UUID) *BookReviewUpdateOne {
	_u.mutation.AddBookIDs(ids...)
	return _u
}

// AddBook adds the "book" edges to the Book entity.
func (_u *BookReviewUpdateOne) AddBook(v ...*Book) *BookReviewUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddBookIDs(ids...)
}

// AddReviewerIDs adds the "reviewer" edge to the User entity by IDs.
func (_u *BookReviewUpdateOne) AddReviewerIDs(ids ...uuid.UUID) *BookReviewUpdateOne {
	_u.mutation.AddReviewerIDs(ids...)
	return _u
}

// AddReviewer adds the "reviewer" edges to the User entity.
func (_u *BookReviewUpdateOne) AddReviewer(v ...*User) *BookReviewUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddReviewerIDs(ids...)
}

// Mutation returns the BookReviewMutation object of the builder.
func (_u *BookReviewUpdateOne) Mutation() *BookReviewMutation {
	return _u.mutation
}

// ClearBook clears all "book" edges to the Book entity.
func (_u *BookReviewUpdateOne) ClearBook() *BookReviewUpdateOne {
	_u.mutation.ClearBook()
	return _u
}

// RemoveBookIDs removes the "book" edge to Book entities by IDs.
func (_u *BookReviewUpdateOne) RemoveBookIDs(ids ...uuid.UUID) *BookReviewUpdateOne {
	_u.mutation.RemoveBookIDs(ids...)
	return _u
}

// RemoveBook removes "book" edges to Book entities.
func (_u *BookReviewUpdateOne) RemoveBook(v ...*Book) *BookReviewUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveBookIDs(ids...)
}

// ClearReviewer clears all "reviewer" edges to the User entity.
func (_u *BookReviewUpdateOne) ClearReviewer() *BookReviewUpdateOne {
	_u.mutation.ClearReviewer()
	return _u
}

// RemoveReviewerIDs removes the "reviewer" edge to User entities by IDs.
func (_u *BookReviewUpdateOne) RemoveReviewerIDs(ids ...uuid.UUID) *BookReviewUpdateOne {
	_u.mutation.RemoveReviewerIDs(ids...)
	return _u
}

// RemoveReviewer removes "reviewer" edges to User entities.
func (_u *BookReviewUpdateOne) RemoveReviewer(v ...*User) *BookReviewUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveReviewerIDs(ids...)
}

// Where appends a list predicates to the BookReviewUpdate builder.
func (_u *BookReviewUpdateOne) Where(ps ...predicate.BookReview) *BookReviewUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *BookReviewUpdateOne) Select(field string, fields ...string) *BookReviewUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated BookReview entity.
func (_u *BookReviewUpdateOne) Save(ctx context.Context) (*BookReview, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *BookReviewUpdateOne) SaveX(ctx context.Context) *BookReview {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *BookReviewUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *BookReviewUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *BookReviewUpdateOne) check() error {
	if v, ok := _u.mutation.Action(); ok {
		if err := bookreview.ActionValidator(v); err != nil {
			return &ValidationError{Name: "action", err: fmt.Errorf(`ent: validator failed for field "BookReview.action": %w`, err)}
		}
	}
	if v, ok := _u.mutation.StatusFrom(); ok {
		if err := bookreview.StatusFromValidator(v); err != nil {
			return &ValidationError{Name: "status_from", err: fmt.Errorf(`ent: validator failed for field "BookReview.status_from": %w`, err)}
		}
	}
	if v, ok := _u.mutation.StatusTo(); ok {
		if err := bookreview.StatusToValidator(v); err != nil {
			return &ValidationError{Name: "status_to", err: fmt.Errorf(`ent: validator failed for field "BookReview.status_to": %w`, err)}
		}
	}
	return nil
}

func (_u *BookReviewUpdateOne) sqlSave(ctx context.Context) (_node *BookReview, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(bookreview.Table, bookreview.Columns, sqlgraph.NewFieldSpec(bookreview.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "BookReview.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, bookreview.FieldID)
		for _, f := range fields {
			if !bookreview.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != bookreview.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.BookID(); ok {
		_spec.SetField(bookreview.FieldBookID, field.TypeUUID, value)
	}
	if value, ok := _u.mutation.ReviewerID(); ok {
		_spec.SetField(bookreview.FieldReviewerID, field.TypeUUID, value)
	}
	if value, ok := _u.mutation.Action(); ok {
		_spec.SetField(bookreview.FieldAction, field.TypeString, value)
	}
	if value, ok := _u.mutation.StatusFrom(); ok {
		_spec.SetField(bookreview.FieldStatusFrom, field.TypeString, value)
	}
	if value, ok := _u.mutation.StatusTo(); ok {
		_spec.SetField(bookreview.FieldStatusTo, field.TypeString, value)
	}
	if value, ok := _u.mutation.Reason(); ok {
		_spec.SetField(bookreview.FieldReason, field.TypeString, value)
	}
	if _u.mutation.ReasonCleared() {
		_spec.ClearField(bookreview.FieldReason, field.TypeString)
	}
	if _u.mutation.BookCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   bookreview.BookTable,
			Columns: []string{bookreview.BookColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(book.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedBookIDs(); len(nodes) > 0 && !_u.mutation.BookCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   bookreview.BookTable,
			Columns: []string{bookreview.BookColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(book.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.BookIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   bookreview.BookTable,
			Columns: []string{bookreview.BookColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(book.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ReviewerCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   bookreview.ReviewerTable,
			Columns: []string{bookreview.ReviewerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedReviewerIDs(); len(nodes) > 0 && !_u.mutation.ReviewerCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   bookreview.ReviewerTable,
			Columns: []string{bookreview.ReviewerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ReviewerIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   bookreview.ReviewerTable,
			Columns: []string{bookreview.ReviewerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &BookReview{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{bookreview.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
