// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/zhoumingjun/bookmgr/backend/ent/book"
	"github.com/zhoumingjun/bookmgr/backend/ent/bookdimension"
	"github.com/zhoumingjun/bookmgr/backend/ent/bookfile"
	"github.com/zhoumingjun/bookmgr/backend/ent/bookreview"
	"github.com/zhoumingjun/bookmgr/backend/ent/predicate"
	"github.com/zhoumingjun/bookmgr/backend/ent/user"
)

// BookUpdate is the builder for updating Book entities.
type BookUpdate struct {
	config
	hooks    []Hook
	mutation *BookMutation
}

// Where appends a list predicates to the BookUpdate builder.
func (_u *BookUpdate) Where(ps ...predicate.Book) *BookUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetTitle sets the "title" field.
func (_u *BookUpdate) SetTitle(v string) *BookUpdate {
	_u.mutation.SetTitle(v)
	return _u
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (_u *BookUpdate) SetNillableTitle(v *string) *BookUpdate {
	if v != nil {
		_u.SetTitle(*v)
	}
	return _u
}

// SetAuthor sets the "author" field.
func (_u *BookUpdate) SetAuthor(v string) *BookUpdate {
	_u.mutation.SetAuthor(v)
	return _u
}

// SetNillableAuthor sets the "author" field if the given value is not nil.
func (_u *BookUpdate) SetNillableAuthor(v *string) *BookUpdate {
	if v != nil {
		_u.SetAuthor(*v)
	}
	return _u
}

// SetDescription sets the "description" field.
func (_u *BookUpdate) SetDescription(v string) *BookUpdate {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *BookUpdate) SetNillableDescription(v *string) *BookUpdate {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// ClearDescription clears the value of the "description" field.
func (_u *BookUpdate) ClearDescription() *BookUpdate {
	_u.mutation.ClearDescription()
	return _u
}

// SetPageCount sets the "page_count" field.
func (_u *BookUpdate) SetPageCount(v int) *BookUpdate {
	_u.mutation.ResetPageCount()
	_u.mutation.SetPageCount(v)
	return _u
}

// SetNillablePageCount sets the "page_count" field if the given value is not nil.
func (_u *BookUpdate) SetNillablePageCount(v *int) *BookUpdate {
	if v != nil {
		_u.SetPageCount(*v)
	}
	return _u
}

// AddPageCount adds value to the "page_count" field.
func (_u *BookUpdate) AddPageCount(v int) *BookUpdate {
	_u.mutation.AddPageCount(v)
	return _u
}

// ClearPageCount clears the value of the "page_count" field.
func (_u *BookUpdate) ClearPageCount() *BookUpdate {
	_u.mutation.ClearPageCount()
	return _u
}

// SetDurationMinutes sets the "duration_minutes" field.
func (_u *BookUpdate) SetDurationMinutes(v int) *BookUpdate {
	_u.mutation.ResetDurationMinutes()
	_u.mutation.SetDurationMinutes(v)
	return _u
}

// SetNillableDurationMinutes sets the "duration_minutes" field if the given value is not nil.
func (_u *BookUpdate) SetNillableDurationMinutes(v *int) *BookUpdate {
	if v != nil {
		_u.SetDurationMinutes(*v)
	}
	return _u
}

// AddDurationMinutes adds value to the "duration_minutes" field.
func (_u *BookUpdate) AddDurationMinutes(v int) *BookUpdate {
	_u.mutation.AddDurationMinutes(v)
	return _u
}

// ClearDurationMinutes clears the value of the "duration_minutes" field.
func (_u *BookUpdate) ClearDurationMinutes() *BookUpdate {
	_u.mutation.ClearDurationMinutes()
	return _u
}

// SetCoreGoal sets the "core_goal" field.
func (_u *BookUpdate) SetCoreGoal(v string) *BookUpdate {
	_u.mutation.SetCoreGoal(v)
	return _u
}

// SetNillableCoreGoal sets the "core_goal" field if the given value is not nil.
func (_u *BookUpdate) SetNillableCoreGoal(v *string) *BookUpdate {
	if v != nil {
		_u.SetCoreGoal(*v)
	}
	return _u
}

// ClearCoreGoal clears the value of the "core_goal" field.
func (_u *BookUpdate) ClearCoreGoal() *BookUpdate {
	_u.mutation.ClearCoreGoal()
	return _u
}

// SetCognitiveLevel sets the "cognitive_level" field.
func (_u *BookUpdate) SetCognitiveLevel(v string) *BookUpdate {
	_u.mutation.SetCognitiveLevel(v)
	return _u
}

// SetNillableCognitiveLevel sets the "cognitive_level" field if the given value is not nil.
func (_u *BookUpdate) SetNillableCognitiveLevel(v *string) *BookUpdate {
	if v != nil {
		_u.SetCognitiveLevel(*v)
	}
	return _u
}

// ClearCognitiveLevel clears the value of the "cognitive_level" field.
func (_u *BookUpdate) ClearCognitiveLevel() *BookUpdate {
	_u.mutation.ClearCognitiveLevel()
	return _u
}

// SetResourceType sets the "resource_type" field.
func (_u *BookUpdate) SetResourceType(v string) *BookUpdate {
	_u.mutation.SetResourceType(v)
	return _u
}

// SetNillableResourceType sets the "resource_type" field if the given value is not nil.
func (_u *BookUpdate) SetNillableResourceType(v *string) *BookUpdate {
	if v != nil {
		_u.SetResourceType(*v)
	}
	return _u
}

// ClearResourceType clears the value of the "resource_type" field.
func (_u *BookUpdate) ClearResourceType() *BookUpdate {
	_u.mutation.ClearResourceType()
	return _u
}

// SetHasPrint sets the "has_print" field.
func (_u *BookUpdate) SetHasPrint(v bool) *BookUpdate {
	_u.mutation.SetHasPrint(v)
	return _u
}

// SetNillableHasPrint sets the "has_print" field if the given value is not nil.
func (_u *BookUpdate) SetNillableHasPrint(v *bool) *BookUpdate {
	if v != nil {
		_u.SetHasPrint(*v)
	}
	return _u
}

// SetHasDigital sets the "has_digital" field.
func (_u *BookUpdate) SetHasDigital(v bool) *BookUpdate {
	_u.mutation.SetHasDigital(v)
	return _u
}

// SetNillableHasDigital sets the "has_digital" field if the given value is not nil.
func (_u *BookUpdate) SetNillableHasDigital(v *bool) *BookUpdate {
	if v != nil {
		_u.SetHasDigital(*v)
	}
	return _u
}

// SetHasAudio sets the "has_audio" field.
func (_u *BookUpdate) SetHasAudio(v bool) *BookUpdate {
	_u.mutation.SetHasAudio(v)
	return _u
}

// SetNillableHasAudio sets the "has_audio" field if the given value is not nil.
func (_u *BookUpdate) SetNillableHasAudio(v *bool) *BookUpdate {
	if v != nil {
		_u.SetHasAudio(*v)
	}
	return _u
}

// SetHasVideo sets the "has_video" field.
func (_u *BookUpdate) SetHasVideo(v bool) *BookUpdate {
	_u.mutation.SetHasVideo(v)
	return _u
}

// SetNillableHasVideo sets the "has_video" field if the given value is not nil.
func (_u *BookUpdate) SetNillableHasVideo(v *bool) *BookUpdate {
	if v != nil {
		_u.SetHasVideo(*v)
	}
	return _u
}

// SetTeachingSuggestion sets the "teaching_suggestion" field.
func (_u *BookUpdate) SetTeachingSuggestion(v string) *BookUpdate {
	_u.mutation.SetTeachingSuggestion(v)
	return _u
}

// SetNillableTeachingSuggestion sets the "teaching_suggestion" field if the given value is not nil.
func (_u *BookUpdate) SetNillableTeachingSuggestion(v *string) *BookUpdate {
	if v != nil {
		_u.SetTeachingSuggestion(*v)
	}
	return _u
}

// ClearTeachingSuggestion clears the value of the "teaching_suggestion" field.
func (_u *BookUpdate) ClearTeachingSuggestion() *BookUpdate {
	_u.mutation.ClearTeachingSuggestion()
	return _u
}

// SetParentReadingGuide sets the "parent_reading_guide" field.
func (_u *BookUpdate) SetParentReadingGuide(v string) *BookUpdate {
	_u.mutation.SetParentReadingGuide(v)
	return _u
}

// SetNillableParentReadingGuide sets the "parent_reading_guide" field if the given value is not nil.
func (_u *BookUpdate) SetNillableParentReadingGuide(v *string) *BookUpdate {
	if v != nil {
		_u.SetParentReadingGuide(*v)
	}
	return _u
}

// ClearParentReadingGuide clears the value of the "parent_reading_guide" field.
func (_u *BookUpdate) ClearParentReadingGuide() *BookUpdate {
	_u.mutation.ClearParentReadingGuide()
	return _u
}

// SetRecommendedAgeMin sets the "recommended_age_min" field.
func (_u *BookUpdate) SetRecommendedAgeMin(v int) *BookUpdate {
	_u.mutation.ResetRecommendedAgeMin()
	_u.mutation.SetRecommendedAgeMin(v)
	return _u
}

// SetNillableRecommendedAgeMin sets the "recommended_age_min" field if the given value is not nil.
func (_u *BookUpdate) SetNillableRecommendedAgeMin(v *int) *BookUpdate {
	if v != nil {
		_u.SetRecommendedAgeMin(*v)
	}
	return _u
}

// AddRecommendedAgeMin adds value to the "recommended_age_min" field.
func (_u *BookUpdate) AddRecommendedAgeMin(v int) *BookUpdate {
	_u.mutation.AddRecommendedAgeMin(v)
	return _u
}

// SetRecommendedAgeMax sets the "recommended_age_max" field.
func (_u *BookUpdate) SetRecommendedAgeMax(v int) *BookUpdate {
	_u.mutation.ResetRecommendedAgeMax()
	_u.mutation.SetRecommendedAgeMax(v)
	return _u
}

// SetNillableRecommendedAgeMax sets the "recommended_age_max" field if the given value is not nil.
func (_u *BookUpdate) SetNillableRecommendedAgeMax(v *int) *BookUpdate {
	if v != nil {
		_u.SetRecommendedAgeMax(*v)
	}
	return _u
}

// AddRecommendedAgeMax adds value to the "recommended_age_max" field.
func (_u *BookUpdate) AddRecommendedAgeMax(v int) *BookUpdate {
	_u.mutation.AddRecommendedAgeMax(v)
	return _u
}

// SetCoverImageURL sets the "cover_image_url" field.
func (_u *BookUpdate) SetCoverImageURL(v string) *BookUpdate {
	_u.mutation.SetCoverImageURL(v)
	return _u
}

// SetNillableCoverImageURL sets the "cover_image_url" field if the given value is not nil.
func (_u *BookUpdate) SetNillableCoverImageURL(v *string) *BookUpdate {
	if v != nil {
		_u.SetCoverImageURL(*v)
	}
	return _u
}

// ClearCoverImageURL clears the value of the "cover_image_url" field.
func (_u *BookUpdate) ClearCoverImageURL() *BookUpdate {
	_u.mutation.ClearCoverImageURL()
	return _u
}

// SetCoverURL sets the "cover_url" field.
func (_u *BookUpdate) SetCoverURL(v string) *BookUpdate {
	_u.mutation.SetCoverURL(v)
	return _u
}

// SetNillableCoverURL sets the "cover_url" field if the given value is not nil.
func (_u *BookUpdate) SetNillableCoverURL(v *string) *BookUpdate {
	if v != nil {
		_u.SetCoverURL(*v)
	}
	return _u
}

// ClearCoverURL clears the value of the "cover_url" field.
func (_u *BookUpdate) ClearCoverURL() *BookUpdate {
	_u.mutation.ClearCoverURL()
	return _u
}

// SetFilePath sets the "file_path" field.
func (_u *BookUpdate) SetFilePath(v string) *BookUpdate {
	_u.mutation.SetFilePath(v)
	return _u
}

// SetNillableFilePath sets the "file_path" field if the given value is not nil.
func (_u *BookUpdate) SetNillableFilePath(v *string) *BookUpdate {
	if v != nil {
		_u.SetFilePath(*v)
	}
	return _u
}

// ClearFilePath clears the value of the "file_path" field.
func (_u *BookUpdate) ClearFilePath() *BookUpdate {
	_u.mutation.ClearFilePath()
	return _u
}

// SetStatus sets the "status" field.
func (_u *BookUpdate) SetStatus(v string) *BookUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *BookUpdate) SetNillableStatus(v *string) *BookUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetUploaderID sets the "uploader_id" field.
func (_u *BookUpdate) SetUploaderID(v uuid.UUID) *BookUpdate {
	_u.mutation.SetUploaderID(v)
	return _u
}

// SetNillableUploaderID sets the "uploader_id" field if the given value is not nil.
func (_u *BookUpdate) SetNillableUploaderID(v *uuid.UUID) *BookUpdate {
	if v != nil {
		_u.SetUploaderID(*v)
	}
	return _u
}

// SetViewCount sets the "view_count" field.
func (_u *BookUpdate) SetViewCount(v int) *BookUpdate {
	_u.mutation.ResetViewCount()
	_u.mutation.SetViewCount(v)
	return _u
}

// SetNillableViewCount sets the "view_count" field if the given value is not nil.
func (_u *BookUpdate) SetNillableViewCount(v *int) *BookUpdate {
	if v != nil {
		_u.SetViewCount(*v)
	}
	return _u
}

// AddViewCount adds value to the "view_count" field.
func (_u *BookUpdate) AddViewCount(v int) *BookUpdate {
	_u.mutation.AddViewCount(v)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *BookUpdate) SetUpdatedAt(v time.Time) *BookUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetUploader sets the "uploader" edge to the User entity.
func (_u *BookUpdate) SetUploader(v *User) *BookUpdate {
	return _u.SetUploaderID(v.ID)
}

// AddBookDimensionIDs adds the "book_dimensions" edge to the BookDimension entity by IDs.
func (_u *BookUpdate) AddBookDimensionIDs(ids ...uuid.UUID) *BookUpdate {
	_u.mutation.AddBookDimensionIDs(ids...)
	return _u
}

// AddBookDimensions adds the "book_dimensions" edges to the BookDimension entity.
func (_u *BookUpdate) AddBookDimensions(v ...*BookDimension) *BookUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddBookDimensionIDs(ids...)
}

// AddFileIDs adds the "files" edge to the BookFile entity by IDs.
func (_u *BookUpdate) AddFileIDs(ids ...uuid.UUID) *BookUpdate {
	_u.mutation.AddFileIDs(ids...)
	return _u
}

// AddFiles adds the "files" edges to the BookFile entity.
func (_u *BookUpdate) AddFiles(v ...*BookFile) *BookUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddFileIDs(ids...)
}

// AddReviewIDs adds the "reviews" edge to the BookReview entity by IDs.
func (_u *BookUpdate) AddReviewIDs(ids ...uuid.UUID) *BookUpdate {
	_u.mutation.AddReviewIDs(ids...)
	return _u
}

// AddReviews adds the "reviews" edges to the BookReview entity.
func (_u *BookUpdate) AddReviews(v ...*BookReview) *BookUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddReviewIDs(ids...)
}

// Mutation returns the BookMutation object of the builder.
func (_u *BookUpdate) Mutation() *BookMutation {
	return _u.mutation
}

// ClearUploader clears the "uploader" edge to the User entity.
func (_u *BookUpdate) ClearUploader() *BookUpdate {
	_u.mutation.ClearUploader()
	return _u
}

// ClearBookDimensions clears all "book_dimensions" edges to the BookDimension entity.
func (_u *BookUpdate) ClearBookDimensions() *BookUpdate {
	_u.mutation.ClearBookDimensions()
	return _u
}

// RemoveBookDimensionIDs removes the "book_dimensions" edge to BookDimension entities by IDs.
func (_u *BookUpdate) RemoveBookDimensionIDs(ids ...uuid.UUID) *BookUpdate {
	_u.mutation.RemoveBookDimensionIDs(ids...)
	return _u
}

// RemoveBookDimensions removes "book_dimensions" edges to BookDimension entities.
func (_u *BookUpdate) RemoveBookDimensions(v ...*BookDimension) *BookUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveBookDimensionIDs(ids...)
}

// ClearFiles clears all "files" edges to the BookFile entity.
func (_u *BookUpdate) ClearFiles() *BookUpdate {
	_u.mutation.ClearFiles()
	return _u
}

// RemoveFileIDs removes the "files" edge to BookFile entities by IDs.
func (_u *BookUpdate) RemoveFileIDs(ids ...uuid.UUID) *BookUpdate {
	_u.mutation.RemoveFileIDs(ids...)
	return _u
}

// RemoveFiles removes "files" edges to BookFile entities.
func (_u *BookUpdate) RemoveFiles(v ...*BookFile) *BookUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveFileIDs(ids...)
}

// ClearReviews clears all "reviews" edges to the BookReview entity.
func (_u *BookUpdate) ClearReviews() *BookUpdate {
	_u.mutation.ClearReviews()
	return _u
}

// RemoveReviewIDs removes the "reviews" edge to BookReview entities by IDs.
func (_u *BookUpdate) RemoveReviewIDs(ids ...uuid.UUID) *BookUpdate {
	_u.mutation.RemoveReviewIDs(ids...)
	return _u
}

// RemoveReviews removes "reviews" edges to BookReview entities.
func (_u *BookUpdate) RemoveReviews(v ...*BookReview) *BookUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveReviewIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *BookUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *BookUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *BookUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *BookUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *BookUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := book.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *BookUpdate) check() error {
	if v, ok := _u.mutation.Title(); ok {
		if err := book.TitleValidator(v); err != nil {
			return &ValidationError{Name: "title", err: fmt.Errorf(`ent: validator failed for field "Book.title": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Author(); ok {
		if err := book.AuthorValidator(v); err != nil {
			return &ValidationError{Name: "author", err: fmt.Errorf(`ent: validator failed for field "Book.author": %w`, err)}
		}
	}
	if v, ok := _u.mutation.CognitiveLevel(); ok {
		if err := book.CognitiveLevelValidator(v); err != nil {
			return &ValidationError{Name: "cognitive_level", err: fmt.Errorf(`ent: validator failed for field "Book.cognitive_level": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ResourceType(); ok {
		if err := book.ResourceTypeValidator(v); err != nil {
			return &ValidationError{Name: "resource_type", err: fmt.Errorf(`ent: validator failed for field "Book.resource_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.CoverImageURL(); ok {
		if err := book.CoverImageURLValidator(v); err != nil {
			return &ValidationError{Name: "cover_image_url", err: fmt.Errorf(`ent: validator failed for field "Book.cover_image_url": %w`, err)}
		}
	}
	if v, ok := _u.mutation.CoverURL(); ok {
		if err := book.CoverURLValidator(v); err != nil {
			return &ValidationError{Name: "cover_url", err: fmt.Errorf(`ent: validator failed for field "Book.cover_url": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := book.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Book.status": %w`, err)}
		}
	}
	if _u.mutation.UploaderCleared() && len(_u.mutation.UploaderIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Book.uploader"`)
	}
	return nil
}

func (_u *BookUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(book.Table, book.Columns, sqlgraph.NewFieldSpec(book.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Title(); ok {
		_spec.SetField(book.FieldTitle, field.TypeString, value)
	}
	if value, ok := _u.mutation.Author(); ok {
		_spec.SetField(book.FieldAuthor, field.TypeString, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(book.FieldDescription, field.TypeString, value)
	}
	if _u.mutation.DescriptionCleared() {
		_spec.ClearField(book.FieldDescription, field.TypeString)
	}
	if value, ok := _u.mutation.PageCount(); ok {
		_spec.SetField(book.FieldPageCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedPageCount(); ok {
		_spec.AddField(book.FieldPageCount, field.TypeInt, value)
	}
	if _u.mutation.PageCountCleared() {
		_spec.ClearField(book.FieldPageCount, field.TypeInt)
	}
	if value, ok := _u.mutation.DurationMinutes(); ok {
		_spec.SetField(book.FieldDurationMinutes, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedDurationMinutes(); ok {
		_spec.AddField(book.FieldDurationMinutes, field.TypeInt, value)
	}
	if _u.mutation.DurationMinutesCleared() {
		_spec.ClearField(book.FieldDurationMinutes, field.TypeInt)
	}
	if value, ok := _u.mutation.CoreGoal(); ok {
		_spec.SetField(book.FieldCoreGoal, field.TypeString, value)
	}
	if _u.mutation.CoreGoalCleared() {
		_spec.ClearField(book.FieldCoreGoal, field.TypeString)
	}
	if value, ok := _u.mutation.CognitiveLevel(); ok {
		_spec.SetField(book.FieldCognitiveLevel, field.TypeString, value)
	}
	if _u.mutation.CognitiveLevelCleared() {
		_spec.ClearField(book.FieldCognitiveLevel, field.TypeString)
	}
	if value, ok := _u.mutation.ResourceType(); ok {
		_spec.SetField(book.FieldResourceType, field.TypeString, value)
	}
	if _u.mutation.ResourceTypeCleared() {
		_spec.ClearField(book.FieldResourceType, field.TypeString)
	}
	if value, ok := _u.mutation.HasPrint(); ok {
		_spec.SetField(book.FieldHasPrint, field.TypeBool, value)
	}
	if value, ok := _u.mutation.HasDigital(); ok {
		_spec.SetField(book.FieldHasDigital, field.TypeBool, value)
	}
	if value, ok := _u.mutation.HasAudio(); ok {
		_spec.SetField(book.FieldHasAudio, field.TypeBool, value)
	}
	if value, ok := _u.mutation.HasVideo(); ok {
		_spec.SetField(book.FieldHasVideo, field.TypeBool, value)
	}
	if value, ok := _u.mutation.TeachingSuggestion(); ok {
		_spec.SetField(book.FieldTeachingSuggestion, field.TypeString, value)
	}
	if _u.mutation.TeachingSuggestionCleared() {
		_spec.ClearField(book.FieldTeachingSuggestion, field.TypeString)
	}
	if value, ok := _u.mutation.ParentReadingGuide(); ok {
		_spec.SetField(book.FieldParentReadingGuide, field.TypeString, value)
	}
	if _u.mutation.ParentReadingGuideCleared() {
		_spec.ClearField(book.FieldParentReadingGuide, field.TypeString)
	}
	if value, ok := _u.mutation.RecommendedAgeMin(); ok {
		_spec.SetField(book.FieldRecommendedAgeMin, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedRecommendedAgeMin(); ok {
		_spec.AddField(book.FieldRecommendedAgeMin, field.TypeInt, value)
	}
	if value, ok := _u.mutation.RecommendedAgeMax(); ok {
		_spec.SetField(book.FieldRecommendedAgeMax, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedRecommendedAgeMax(); ok {
		_spec.AddField(book.FieldRecommendedAgeMax, field.TypeInt, value)
	}
	if value, ok := _u.mutation.CoverImageURL(); ok {
		_spec.SetField(book.FieldCoverImageURL, field.TypeString, value)
	}
	if _u.mutation.CoverImageURLCleared() {
		_spec.ClearField(book.FieldCoverImageURL, field.TypeString)
	}
	if value, ok := _u.mutation.CoverURL(); ok {
		_spec.SetField(book.FieldCoverURL, field.TypeString, value)
	}
	if _u.mutation.CoverURLCleared() {
		_spec.ClearField(book.FieldCoverURL, field.TypeString)
	}
	if value, ok := _u.mutation.FilePath(); ok {
		_spec.SetField(book.FieldFilePath, field.TypeString, value)
	}
	if _u.mutation.FilePathCleared() {
		_spec.ClearField(book.FieldFilePath, field.TypeString)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(book.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.ViewCount(); ok {
		_spec.SetField(book.FieldViewCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedViewCount(); ok {
		_spec.AddField(book.FieldViewCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(book.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.UploaderCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   book.UploaderTable,
			Columns: []string{book.UploaderColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UploaderIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   book.UploaderTable,
			Columns: []string{book.UploaderColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.BookDimensionsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   book.BookDimensionsTable,
			Columns: book.BookDimensionsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(bookdimension.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedBookDimensionsIDs(); len(nodes) > 0 && !_u.mutation.BookDimensionsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   book.BookDimensionsTable,
			Columns: book.BookDimensionsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(bookdimension.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.BookDimensionsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   book.BookDimensionsTable,
			Columns: book.BookDimensionsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(bookdimension.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.FilesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   book.FilesTable,
			Columns: book.FilesPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(bookfile.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedFilesIDs(); len(nodes) > 0 && !_u.mutation.FilesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   book.FilesTable,
			Columns: book.FilesPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(bookfile.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.FilesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   book.FilesTable,
			Columns: book.FilesPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(bookfile.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ReviewsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   book.ReviewsTable,
			Columns: []string{book.ReviewsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(bookreview.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedReviewsIDs(); len(nodes) > 0 && !_u.mutation.ReviewsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   book.ReviewsTable,
			Columns: []string{book.ReviewsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(bookreview.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ReviewsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   book.ReviewsTable,
			Columns: []string{book.ReviewsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(bookreview.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{book.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// BookUpdateOne is the builder for updating a single Book entity.
type BookUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *BookMutation
}

// SetTitle sets the "title" field.
func (_u *BookUpdateOne) SetTitle(v string) *BookUpdateOne {
	_u.mutation.SetTitle(v)
	return _u
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (_u *BookUpdateOne) SetNillableTitle(v *string) *BookUpdateOne {
	if v != nil {
		_u.SetTitle(*v)
	}
	return _u
}

// SetAuthor sets the "author" field.
func (_u *BookUpdateOne) SetAuthor(v string) *BookUpdateOne {
	_u.mutation.SetAuthor(v)
	return _u
}

// SetNillableAuthor sets the "author" field if the given value is not nil.
func (_u *BookUpdateOne) SetNillableAuthor(v *string) *BookUpdateOne {
	if v != nil {
		_u.SetAuthor(*v)
	}
	return _u
}

// SetDescription sets the "description" field.
func (_u *BookUpdateOne) SetDescription(v string) *BookUpdateOne {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *BookUpdateOne) SetNillableDescription(v *string) *BookUpdateOne {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// ClearDescription clears the value of the "description" field.
func (_u *BookUpdateOne) ClearDescription() *BookUpdateOne {
	_u.mutation.ClearDescription()
	return _u
}

// SetPageCount sets the "page_count" field.
func (_u *BookUpdateOne) SetPageCount(v int) *BookUpdateOne {
	_u.mutation.ResetPageCount()
	_u.mutation.SetPageCount(v)
	return _u
}

// SetNillablePageCount sets the "page_count" field if the given value is not nil.
func (_u *BookUpdateOne) SetNillablePageCount(v *int) *BookUpdateOne {
	if v != nil {
		_u.SetPageCount(*v)
	}
	return _u
}

// AddPageCount adds value to the "page_count" field.
func (_u *BookUpdateOne) AddPageCount(v int) *BookUpdateOne {
	_u.mutation.AddPageCount(v)
	return _u
}

// ClearPageCount clears the value of the "page_count" field.
func (_u *BookUpdateOne) ClearPageCount() *BookUpdateOne {
	_u.mutation.ClearPageCount()
	return _u
}

// SetDurationMinutes sets the "duration_minutes" field.
func (_u *BookUpdateOne) SetDurationMinutes(v int) *BookUpdateOne {
	_u.mutation.ResetDurationMinutes()
	_u.mutation.SetDurationMinutes(v)
	return _u
}

// SetNillableDurationMinutes sets the "duration_minutes" field if the given value is not nil.
func (_u *BookUpdateOne) SetNillableDurationMinutes(v *int) *BookUpdateOne {
	if v != nil {
		_u.SetDurationMinutes(*v)
	}
	return _u
}

// AddDurationMinutes adds value to the "duration_minutes" field.
func (_u *BookUpdateOne) AddDurationMinutes(v int) *BookUpdateOne {
	_u.mutation.AddDurationMinutes(v)
	return _u
}

// ClearDurationMinutes clears the value of the "duration_minutes" field.
func (_u *BookUpdateOne) ClearDurationMinutes() *BookUpdateOne {
	_u.mutation.ClearDurationMinutes()
	return _u
}

// SetCoreGoal sets the "core_goal" field.
func (_u *BookUpdateOne) SetCoreGoal(v string) *BookUpdateOne {
	_u.mutation.SetCoreGoal(v)
	return _u
}

// SetNillableCoreGoal sets the "core_goal" field if the given value is not nil.
func (_u *BookUpdateOne) SetNillableCoreGoal(v *string) *BookUpdateOne {
	if v != nil {
		_u.SetCoreGoal(*v)
	}
	return _u
}

// ClearCoreGoal clears the value of the "core_goal" field.
func (_u *BookUpdateOne) ClearCoreGoal() *BookUpdateOne {
	_u.mutation.ClearCoreGoal()
	return _u
}

// SetCognitiveLevel sets the "cognitive_level" field.
func (_u *BookUpdateOne) SetCognitiveLevel(v string) *BookUpdateOne {
	_u.mutation.SetCognitiveLevel(v)
	return _u
}

// SetNillableCognitiveLevel sets the "cognitive_level" field if the given value is not nil.
func (_u *BookUpdateOne) SetNillableCognitiveLevel(v *string) *BookUpdateOne {
	if v != nil {
		_u.SetCognitiveLevel(*v)
	}
	return _u
}

// ClearCognitiveLevel clears the value of the "cognitive_level" field.
func (_u *BookUpdateOne) ClearCognitiveLevel() *BookUpdateOne {
	_u.mutation.ClearCognitiveLevel()
	return _u
}

// SetResourceType sets the "resource_type" field.
func (_u *BookUpdateOne) SetResourceType(v string) *BookUpdateOne {
	_u.mutation.SetResourceType(v)
	return _u
}

// SetNillableResourceType sets the "resource_type" field if the given value is not nil.
func (_u *BookUpdateOne) SetNillableResourceType(v *string) *BookUpdateOne {
	if v != nil {
		_u.SetResourceType(*v)
	}
	return _u
}

// ClearResourceType clears the value of the "resource_type" field.
func (_u *BookUpdateOne) ClearResourceType() *BookUpdateOne {
	_u.mutation.ClearResourceType()
	return _u
}

// SetHasPrint sets the "has_print" field.
func (_u *BookUpdateOne) SetHasPrint(v bool) *BookUpdateOne {
	_u.mutation.SetHasPrint(v)
	return _u
}

// SetNillableHasPrint sets the "has_print" field if the given value is not nil.
func (_u *BookUpdateOne) SetNillableHasPrint(v *bool) *BookUpdateOne {
	if v != nil {
		_u.SetHasPrint(*v)
	}
	return _u
}

// SetHasDigital sets the "has_digital" field.
func (_u *BookUpdateOne) SetHasDigital(v bool) *BookUpdateOne {
	_u.mutation.SetHasDigital(v)
	return _u
}

// SetNillableHasDigital sets the "has_digital" field if the given value is not nil.
func (_u *BookUpdateOne) SetNillableHasDigital(v *bool) *BookUpdateOne {
	if v != nil {
		_u.SetHasDigital(*v)
	}
	return _u
}

// SetHasAudio sets the "has_audio" field.
func (_u *BookUpdateOne) SetHasAudio(v bool) *BookUpdateOne {
	_u.mutation.SetHasAudio(v)
	return _u
}

// SetNillableHasAudio sets the "has_audio" field if the given value is not nil.
func (_u *BookUpdateOne) SetNillableHasAudio(v *bool) *BookUpdateOne {
	if v != nil {
		_u.SetHasAudio(*v)
	}
	return _u
}

// SetHasVideo sets the "has_video" field.
func (_u *BookUpdateOne) SetHasVideo(v bool) *BookUpdateOne {
	_u.mutation.SetHasVideo(v)
	return _u
}

// SetNillableHasVideo sets the "has_video" field if the given value is not nil.
func (_u *BookUpdateOne) SetNillableHasVideo(v *bool) *BookUpdateOne {
	if v != nil {
		_u.SetHasVideo(*v)
	}
	return _u
}

// SetTeachingSuggestion sets the "teaching_suggestion" field.
func (_u *BookUpdateOne) SetTeachingSuggestion(v string) *BookUpdateOne {
	_u.mutation.SetTeachingSuggestion(v)
	return _u
}

// SetNillableTeachingSuggestion sets the "teaching_suggestion" field if the given value is not nil.
func (_u *BookUpdateOne) SetNillableTeachingSuggestion(v *string) *BookUpdateOne {
	if v != nil {
		_u.SetTeachingSuggestion(*v)
	}
	return _u
}

// ClearTeachingSuggestion clears the value of the "teaching_suggestion" field.
func (_u *BookUpdateOne) ClearTeachingSuggestion() *BookUpdateOne {
	_u.mutation.ClearTeachingSuggestion()
	return _u
}

// SetParentReadingGuide sets the "parent_reading_guide" field.
func (_u *BookUpdateOne) SetParentReadingGuide(v string) *BookUpdateOne {
	_u.mutation.SetParentReadingGuide(v)
	return _u
}

// SetNillableParentReadingGuide sets the "parent_reading_guide" field if the given value is not nil.
func (_u *BookUpdateOne) SetNillableParentReadingGuide(v *string) *BookUpdateOne {
	if v != nil {
		_u.SetParentReadingGuide(*v)
	}
	return _u
}

// ClearParentReadingGuide clears the value of the "parent_reading_guide" field.
func (_u *BookUpdateOne) ClearParentReadingGuide() *BookUpdateOne {
	_u.mutation.ClearParentReadingGuide()
	return _u
}

// SetRecommendedAgeMin sets the "recommended_age_min" field.
func (_u *BookUpdateOne) SetRecommendedAgeMin(v int) *BookUpdateOne {
	_u.mutation.ResetRecommendedAgeMin()
	_u.mutation.SetRecommendedAgeMin(v)
	return _u
}

// SetNillableRecommendedAgeMin sets the "recommended_age_min" field if the given value is not nil.
func (_u *BookUpdateOne) SetNillableRecommendedAgeMin(v *int) *BookUpdateOne {
	if v != nil {
		_u.SetRecommendedAgeMin(*v)
	}
	return _u
}

// AddRecommendedAgeMin adds value to the "recommended_age_min" field.
func (_u *BookUpdateOne) AddRecommendedAgeMin(v int) *BookUpdateOne {
	_u.mutation.AddRecommendedAgeMin(v)
	return _u
}

// SetRecommendedAgeMax sets the "recommended_age_max" field.
func (_u *BookUpdateOne) SetRecommendedAgeMax(v int) *BookUpdateOne {
	_u.mutation.ResetRecommendedAgeMax()
	_u.mutation.SetRecommendedAgeMax(v)
	return _u
}

// SetNillableRecommendedAgeMax sets the "recommended_age_max" field if the given value is not nil.
func (_u *BookUpdateOne) SetNillableRecommendedAgeMax(v *int) *BookUpdateOne {
	if v != nil {
		_u.SetRecommendedAgeMax(*v)
	}
	return _u
}

// AddRecommendedAgeMax adds value to the "recommended_age_max" field.
func (_u *BookUpdateOne) AddRecommendedAgeMax(v int) *BookUpdateOne {
	_u.mutation.AddRecommendedAgeMax(v)
	return _u
}

// SetCoverImageURL sets the "cover_image_url" field.
func (_u *BookUpdateOne) SetCoverImageURL(v string) *BookUpdateOne {
	_u.mutation.SetCoverImageURL(v)
	return _u
}

// SetNillableCoverImageURL sets the "cover_image_url" field if the given value is not nil.
func (_u *BookUpdateOne) SetNillableCoverImageURL(v *string) *BookUpdateOne {
	if v != nil {
		_u.SetCoverImageURL(*v)
	}
	return _u
}

// ClearCoverImageURL clears the value of the "cover_image_url" field.
func (_u *BookUpdateOne) ClearCoverImageURL() *BookUpdateOne {
	_u.mutation.ClearCoverImageURL()
	return _u
}

// SetCoverURL sets the "cover_url" field.
func (_u *BookUpdateOne) SetCoverURL(v string) *BookUpdateOne {
	_u.mutation.SetCoverURL(v)
	return _u
}

// SetNillableCoverURL sets the "cover_url" field if the given value is not nil.
func (_u *BookUpdateOne) SetNillableCoverURL(v *string) *BookUpdateOne {
	if v != nil {
		_u.SetCoverURL(*v)
	}
	return _u
}

// ClearCoverURL clears the value of the "cover_url" field.
func (_u *BookUpdateOne) ClearCoverURL() *BookUpdateOne {
	_u.mutation.ClearCoverURL()
	return _u
}

// SetFilePath sets the "file_path" field.
func (_u *BookUpdateOne) SetFilePath(v string) *BookUpdateOne {
	_u.mutation.SetFilePath(v)
	return _u
}

// SetNillableFilePath sets the "file_path" field if the given value is not nil.
func (_u *BookUpdateOne) SetNillableFilePath(v *string) *BookUpdateOne {
	if v != nil {
		_u.SetFilePath(*v)
	}
	return _u
}

// ClearFilePath clears the value of the "file_path" field.
func (_u *BookUpdateOne) ClearFilePath() *BookUpdateOne {
	_u.mutation.ClearFilePath()
	return _u
}

// SetStatus sets the "status" field.
func (_u *BookUpdateOne) SetStatus(v string) *BookUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *BookUpdateOne) SetNillableStatus(v *string) *BookUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetUploaderID sets the "uploader_id" field.
func (_u *BookUpdateOne) SetUploaderID(v uuid.UUID) *BookUpdateOne {
	_u.mutation.SetUploaderID(v)
	return _u
}

// SetNillableUploaderID sets the "uploader_id" field if the given value is not nil.
func (_u *BookUpdateOne) SetNillableUploaderID(v *uuid.UUID) *BookUpdateOne {
	if v != nil {
		_u.SetUploaderID(*v)
	}
	return _u
}

// SetViewCount sets the "view_count" field.
func (_u *BookUpdateOne) SetViewCount(v int) *BookUpdateOne {
	_u.mutation.ResetViewCount()
	_u.mutation.SetViewCount(v)
	return _u
}

// SetNillableViewCount sets the "view_count" field if the given value is not nil.
func (_u *BookUpdateOne) SetNillableViewCount(v *int) *BookUpdateOne {
	if v != nil {
		_u.SetViewCount(*v)
	}
	return _u
}

// AddViewCount adds value to the "view_count" field.
func (_u *BookUpdateOne) AddViewCount(v int) *BookUpdateOne {
	_u.mutation.AddViewCount(v)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *BookUpdateOne) SetUpdatedAt(v time.Time) *BookUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetUploader sets the "uploader" edge to the User entity.
func (_u *BookUpdateOne) SetUploader(v *User) *BookUpdateOne {
	return _u.SetUploaderID(v.ID)
}

// AddBookDimensionIDs adds the "book_dimensions" edge to the BookDimension entity by IDs.
func (_u *BookUpdateOne) AddBookDimensionIDs(ids ...uuid.UUID) *BookUpdateOne {
	_u.mutation.AddBookDimensionIDs(ids...)
	return _u
}

// AddBookDimensions adds the "book_dimensions" edges to the BookDimension entity.
func (_u *BookUpdateOne) AddBookDimensions(v ...*BookDimension) *BookUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddBookDimensionIDs(ids...)
}

// AddFileIDs adds the "files" edge to the BookFile entity by IDs.
func (_u *BookUpdateOne) AddFileIDs(ids ...uuid.UUID) *BookUpdateOne {
	_u.mutation.AddFileIDs(ids...)
	return _u
}

// AddFiles adds the "files" edges to the BookFile entity.
func (_u *BookUpdateOne) AddFiles(v ...*BookFile) *BookUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddFileIDs(ids...)
}

// AddReviewIDs adds the "reviews" edge to the BookReview entity by IDs.
func (_u *BookUpdateOne) AddReviewIDs(ids ...uuid.UUID) *BookUpdateOne {
	_u.mutation.AddReviewIDs(ids...)
	return _u
}

// AddReviews adds the "reviews" edges to the BookReview entity.
func (_u *BookUpdateOne) AddReviews(v ...*BookReview) *BookUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddReviewIDs(ids...)
}

// Mutation returns the BookMutation object of the builder.
func (_u *BookUpdateOne) Mutation() *BookMutation {
	return _u.mutation
}

// ClearUploader clears the "uploader" edge to the User entity.
func (_u *BookUpdateOne) ClearUploader() *BookUpdateOne {
	_u.mutation.ClearUploader()
	return _u
}

// ClearBookDimensions clears all "book_dimensions" edges to the BookDimension entity.
func (_u *BookUpdateOne) ClearBookDimensions() *BookUpdateOne {
	_u.mutation.ClearBookDimensions()
	return _u
}

// RemoveBookDimensionIDs removes the "book_dimensions" edge to BookDimension entities by IDs.
func (_u *BookUpdateOne) RemoveBookDimensionIDs(ids ...uuid.UUID) *BookUpdateOne {
	_u.mutation.RemoveBookDimensionIDs(ids...)
	return _u
}

// RemoveBookDimensions removes "book_dimensions" edges to BookDimension entities.
func (_u *BookUpdateOne) RemoveBookDimensions(v ...*BookDimension) *BookUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveBookDimensionIDs(ids...)
}

// ClearFiles clears all "files" edges to the BookFile entity.
func (_u *BookUpdateOne) ClearFiles() *BookUpdateOne {
	_u.mutation.ClearFiles()
	return _u
}

// RemoveFileIDs removes the "files" edge to BookFile entities by IDs.
func (_u *BookUpdateOne) RemoveFileIDs(ids ...uuid.UUID) *BookUpdateOne {
	_u.mutation.RemoveFileIDs(ids...)
	return _u
}

// RemoveFiles removes "files" edges to BookFile entities.
func (_u *BookUpdateOne) RemoveFiles(v ...*BookFile) *BookUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveFileIDs(ids...)
}

// ClearReviews clears all "reviews" edges to the BookReview entity.
func (_u *BookUpdateOne) ClearReviews() *BookUpdateOne {
	_u.mutation.ClearReviews()
	return _u
}

// RemoveReviewIDs removes the "reviews" edge to BookReview entities by IDs.
func (_u *BookUpdateOne) RemoveReviewIDs(ids ...uuid.UUID) *BookUpdateOne {
	_u.mutation.RemoveReviewIDs(ids...)
	return _u
}

// RemoveReviews removes "reviews" edges to BookReview entities.
func (_u *BookUpdateOne) RemoveReviews(v ...*BookReview) *BookUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveReviewIDs(ids...)
}

// Where appends a list predicates to the BookUpdate builder.
func (_u *BookUpdateOne) Where(ps ...predicate.Book) *BookUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *BookUpdateOne) Select(field string, fields ...string) *BookUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Book entity.
func (_u *BookUpdateOne) Save(ctx context.Context) (*Book, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *BookUpdateOne) SaveX(ctx context.Context) *Book {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *BookUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *BookUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *BookUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := book.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *BookUpdateOne) check() error {
	if v, ok := _u.mutation.Title(); ok {
		if err := book.TitleValidator(v); err != nil {
			return &ValidationError{Name: "title", err: fmt.Errorf(`ent: validator failed for field "Book.title": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Author(); ok {
		if err := book.AuthorValidator(v); err != nil {
			return &ValidationError{Name: "author", err: fmt.Errorf(`ent: validator failed for field "Book.author": %w`, err)}
		}
	}
	if v, ok := _u.mutation.CognitiveLevel(); ok {
		if err := book.CognitiveLevelValidator(v); err != nil {
			return &ValidationError{Name: "cognitive_level", err: fmt.Errorf(`ent: validator failed for field "Book.cognitive_level": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ResourceType(); ok {
		if err := book.ResourceTypeValidator(v); err != nil {
			return &ValidationError{Name: "resource_type", err: fmt.Errorf(`ent: validator failed for field "Book.resource_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.CoverImageURL(); ok {
		if err := book.CoverImageURLValidator(v); err != nil {
			return &ValidationError{Name: "cover_image_url", err: fmt.Errorf(`ent: validator failed for field "Book.cover_image_url": %w`, err)}
		}
	}
	if v, ok := _u.mutation.CoverURL(); ok {
		if err := book.CoverURLValidator(v); err != nil {
			return &ValidationError{Name: "cover_url", err: fmt.Errorf(`ent: validator failed for field "Book.cover_url": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := book.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Book.status": %w`, err)}
		}
	}
	if _u.mutation.UploaderCleared() && len(_u.mutation.UploaderIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Book.uploader"`)
	}
	return nil
}

func (_u *BookUpdateOne) sqlSave(ctx context.Context) (_node *Book, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(book.Table, book.Columns, sqlgraph.NewFieldSpec(book.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Book.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, book.FieldID)
		for _, f := range fields {
			if !book.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != book.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Title(); ok {
		_spec.SetField(book.FieldTitle, field.TypeString, value)
	}
	if value, ok := _u.mutation.Author(); ok {
		_spec.SetField(book.FieldAuthor, field.TypeString, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(book.FieldDescription, field.TypeString, value)
	}
	if _u.mutation.DescriptionCleared() {
		_spec.ClearField(book.FieldDescription, field.TypeString)
	}
	if value, ok := _u.mutation.PageCount(); ok {
		_spec.SetField(book.FieldPageCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedPageCount(); ok {
		_spec.AddField(book.FieldPageCount, field.TypeInt, value)
	}
	if _u.mutation.PageCountCleared() {
		_spec.ClearField(book.FieldPageCount, field.TypeInt)
	}
	if value, ok := _u.mutation.DurationMinutes(); ok {
		_spec.SetField(book.FieldDurationMinutes, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedDurationMinutes(); ok {
		_spec.AddField(book.FieldDurationMinutes, field.TypeInt, value)
	}
	if _u.mutation.DurationMinutesCleared() {
		_spec.ClearField(book.FieldDurationMinutes, field.TypeInt)
	}
	if value, ok := _u.mutation.CoreGoal(); ok {
		_spec.SetField(book.FieldCoreGoal, field.TypeString, value)
	}
	if _u.mutation.CoreGoalCleared() {
		_spec.ClearField(book.FieldCoreGoal, field.TypeString)
	}
	if value, ok := _u.mutation.CognitiveLevel(); ok {
		_spec.SetField(book.FieldCognitiveLevel, field.TypeString, value)
	}
	if _u.mutation.CognitiveLevelCleared() {
		_spec.ClearField(book.FieldCognitiveLevel, field.TypeString)
	}
	if value, ok := _u.mutation.ResourceType(); ok {
		_spec.SetField(book.FieldResourceType, field.TypeString, value)
	}
	if _u.mutation.ResourceTypeCleared() {
		_spec.ClearField(book.FieldResourceType, field.TypeString)
	}
	if value, ok := _u.mutation.HasPrint(); ok {
		_spec.SetField(book.FieldHasPrint, field.TypeBool, value)
	}
	if value, ok := _u.mutation.HasDigital(); ok {
		_spec.SetField(book.FieldHasDigital, field.TypeBool, value)
	}
	if value, ok := _u.mutation.HasAudio(); ok {
		_spec.SetField(book.FieldHasAudio, field.TypeBool, value)
	}
	if value, ok := _u.mutation.HasVideo(); ok {
		_spec.SetField(book.FieldHasVideo, field.TypeBool, value)
	}
	if value, ok := _u.mutation.TeachingSuggestion(); ok {
		_spec.SetField(book.FieldTeachingSuggestion, field.TypeString, value)
	}
	if _u.mutation.TeachingSuggestionCleared() {
		_spec.ClearField(book.FieldTeachingSuggestion, field.TypeString)
	}
	if value, ok := _u.mutation.ParentReadingGuide(); ok {
		_spec.SetField(book.FieldParentReadingGuide, field.TypeString, value)
	}
	if _u.mutation.ParentReadingGuideCleared() {
		_spec.ClearField(book.FieldParentReadingGuide, field.TypeString)
	}
	if value, ok := _u.mutation.RecommendedAgeMin(); ok {
		_spec.SetField(book.FieldRecommendedAgeMin, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedRecommendedAgeMin(); ok {
		_spec.AddField(book.FieldRecommendedAgeMin, field.TypeInt, value)
	}
	if value, ok := _u.mutation.RecommendedAgeMax(); ok {
		_spec.SetField(book.FieldRecommendedAgeMax, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedRecommendedAgeMax(); ok {
		_spec.AddField(book.FieldRecommendedAgeMax, field.TypeInt, value)
	}
	if value, ok := _u.mutation.CoverImageURL(); ok {
		_spec.SetField(book.FieldCoverImageURL, field.TypeString, value)
	}
	if _u.mutation.CoverImageURLCleared() {
		_spec.ClearField(book.FieldCoverImageURL, field.TypeString)
	}
	if value, ok := _u.mutation.CoverURL(); ok {
		_spec.SetField(book.FieldCoverURL, field.TypeString, value)
	}
	if _u.mutation.CoverURLCleared() {
		_spec.ClearField(book.FieldCoverURL, field.TypeString)
	}
	if value, ok := _u.mutation.FilePath(); ok {
		_spec.SetField(book.FieldFilePath, field.TypeString, value)
	}
	if _u.mutation.FilePathCleared() {
		_spec.ClearField(book.FieldFilePath, field.TypeString)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(book.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.ViewCount(); ok {
		_spec.SetField(book.FieldViewCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedViewCount(); ok {
		_spec.AddField(book.FieldViewCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(book.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.UploaderCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   book.UploaderTable,
			Columns: []string{book.UploaderColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UploaderIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   book.UploaderTable,
			Columns: []string{book.UploaderColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.BookDimensionsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   book.BookDimensionsTable,
			Columns: book.BookDimensionsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(bookdimension.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedBookDimensionsIDs(); len(nodes) > 0 && !_u.mutation.BookDimensionsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   book.BookDimensionsTable,
			Columns: book.BookDimensionsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(bookdimension.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.BookDimensionsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   book.BookDimensionsTable,
			Columns: book.BookDimensionsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(bookdimension.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.FilesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   book.FilesTable,
			Columns: book.FilesPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(bookfile.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedFilesIDs(); len(nodes) > 0 && !_u.mutation.FilesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   book.FilesTable,
			Columns: book.FilesPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(bookfile.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.FilesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   book.FilesTable,
			Columns: book.FilesPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(bookfile.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ReviewsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   book.ReviewsTable,
			Columns: []string{book.ReviewsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(bookreview.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedReviewsIDs(); len(nodes) > 0 && !_u.mutation.ReviewsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   book.ReviewsTable,
			Columns: []string{book.ReviewsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(bookreview.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ReviewsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   book.ReviewsTable,
			Columns: []string{book.ReviewsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(bookreview.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Book{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{book.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
