// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
	"github.com/zhoumingjun/bookmgr/backend/ent/bookreadingprogress"
)

// BookReadingProgress is the model entity for the BookReadingProgress schema.
type BookReadingProgress struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// BookID holds the value of the "book_id" field.
	BookID uuid.UUID `json:"book_id,omitempty"`
	// UserID holds the value of the "user_id" field.
	UserID uuid.UUID `json:"user_id,omitempty"`
	// ProgressPercent holds the value of the "progress_percent" field.
	ProgressPercent int `json:"progress_percent,omitempty"`
	// LastPage holds the value of the "last_page" field.
	LastPage int `json:"last_page,omitempty"`
	// LastReadAt holds the value of the "last_read_at" field.
	LastReadAt time.Time `json:"last_read_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the BookReadingProgressQuery when eager-loading is set.
	Edges        BookReadingProgressEdges `json:"edges"`
	selectValues sql.SelectValues
}

// BookReadingProgressEdges holds the relations/edges for other nodes in the graph.
type BookReadingProgressEdges struct {
	// Book holds the value of the book edge.
	Book []*Book `json:"book,omitempty"`
	// User holds the value of the user edge.
	User []*User `json:"user,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// BookOrErr returns the Book value or an error if the edge
// was not loaded in eager-loading.
func (e BookReadingProgressEdges) BookOrErr() ([]*Book, error) {
	if e.loadedTypes[0] {
		return e.Book, nil
	}
	return nil, &NotLoadedError{edge: "book"}
}

// UserOrErr returns the User value or an error if the edge
// was not loaded in eager-loading.
func (e BookReadingProgressEdges) UserOrErr() ([]*User, error) {
	if e.loadedTypes[1] {
		return e.User, nil
	}
	return nil, &NotLoadedError{edge: "user"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*BookReadingProgress) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case bookreadingprogress.FieldProgressPercent, bookreadingprogress.FieldLastPage:
			values[i] = new(sql.NullInt64)
		case bookreadingprogress.FieldLastReadAt:
			values[i] = new(sql.NullTime)
		case bookreadingprogress.FieldID, bookreadingprogress.FieldBookID, bookreadingprogress.FieldUserID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the BookReadingProgress fields.
func (_m *BookReadingProgress) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case bookreadingprogress.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case bookreadingprogress.FieldBookID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field book_id", values[i])
			} else if value != nil {
				_m.BookID = *value
			}
		case bookreadingprogress.FieldUserID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field user_id", values[i])
			} else if value != nil {
				_m.UserID = *value
			}
		case bookreadingprogress.FieldProgressPercent:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field progress_percent", values[i])
			} else if value.Valid {
				_m.ProgressPercent = int(value.Int64)
			}
		case bookreadingprogress.FieldLastPage:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field last_page", values[i])
			} else if value.Valid {
				_m.LastPage = int(value.Int64)
			}
		case bookreadingprogress.FieldLastReadAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field last_read_at", values[i])
			} else if value.Valid {
				_m.LastReadAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the BookReadingProgress.
// This includes values selected through modifiers, order, etc.
func (_m *BookReadingProgress) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryBook queries the "book" edge of the BookReadingProgress entity.
func (_m *BookReadingProgress) QueryBook() *BookQuery {
	return NewBookReadingProgressClient(_m.config).QueryBook(_m)
}

// QueryUser queries the "user" edge of the BookReadingProgress entity.
func (_m *BookReadingProgress) QueryUser() *UserQuery {
	return NewBookReadingProgressClient(_m.config).QueryUser(_m)
}

// Update returns a builder for updating this BookReadingProgress.
// Note that you need to call BookReadingProgress.Unwrap() before calling this method if this BookReadingProgress
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *BookReadingProgress) Update() *BookReadingProgressUpdateOne {
	return NewBookReadingProgressClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the BookReadingProgress entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *BookReadingProgress) Unwrap() *BookReadingProgress {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: BookReadingProgress is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *BookReadingProgress) String() string {
	var builder strings.Builder
	builder.WriteString("BookReadingProgress(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("book_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.BookID))
	builder.WriteString(", ")
	builder.WriteString("user_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.UserID))
	builder.WriteString(", ")
	builder.WriteString("progress_percent=")
	builder.WriteString(fmt.Sprintf("%v", _m.ProgressPercent))
	builder.WriteString(", ")
	builder.WriteString("last_page=")
	builder.WriteString(fmt.Sprintf("%v", _m.LastPage))
	builder.WriteString(", ")
	builder.WriteString("last_read_at=")
	builder.WriteString(_m.LastReadAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// BookReadingProgresses is a parsable slice of BookReadingProgress.
type BookReadingProgresses []*BookReadingProgress
