// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/zhoumingjun/bookmgr/backend/ent/book"
	"github.com/zhoumingjun/bookmgr/backend/ent/bookfeedback"
	"github.com/zhoumingjun/bookmgr/backend/ent/predicate"
	"github.com/zhoumingjun/bookmgr/backend/ent/user"
)

// BookFeedbackUpdate is the builder for updating BookFeedback entities.
type BookFeedbackUpdate struct {
	config
	hooks    []Hook
	mutation *BookFeedbackMutation
}

// Where appends a list predicates to the BookFeedbackUpdate builder.
func (_u *BookFeedbackUpdate) Where(ps ...predicate.BookFeedback) *BookFeedbackUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *BookFeedbackUpdate) SetUserID(v uuid.UUID) *BookFeedbackUpdate {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *BookFeedbackUpdate) SetNillableUserID(v *uuid.UUID) *BookFeedbackUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetBookID sets the "book_id" field.
func (_u *BookFeedbackUpdate) SetBookID(v uuid.UUID) *BookFeedbackUpdate {
	_u.mutation.SetBookID(v)
	return _u
}

// SetNillableBookID sets the "book_id" field if the given value is not nil.
func (_u *BookFeedbackUpdate) SetNillableBookID(v *uuid.UUID) *BookFeedbackUpdate {
	if v != nil {
		_u.SetBookID(*v)
	}
	return _u
}

// SetFeedbackType sets the "feedback_type" field.
func (_u *BookFeedbackUpdate) SetFeedbackType(v bookfeedback.FeedbackType) *BookFeedbackUpdate {
	_u.mutation.SetFeedbackType(v)
	return _u
}

// SetNillableFeedbackType sets the "feedback_type" field if the given value is not nil.
func (_u *BookFeedbackUpdate) SetNillableFeedbackType(v *bookfeedback.FeedbackType) *BookFeedbackUpdate {
	if v != nil {
		_u.SetFeedbackType(*v)
	}
	return _u
}

// SetDifficultyRating sets the "difficulty_rating" field.
func (_u *BookFeedbackUpdate) SetDifficultyRating(v int) *BookFeedbackUpdate {
	_u.mutation.ResetDifficultyRating()
	_u.mutation.SetDifficultyRating(v)
	return _u
}

// SetNillableDifficultyRating sets the "difficulty_rating" field if the given value is not nil.
func (_u *BookFeedbackUpdate) SetNillableDifficultyRating(v *int) *BookFeedbackUpdate {
	if v != nil {
		_u.SetDifficultyRating(*v)
	}
	return _u
}

// AddDifficultyRating adds value to the "difficulty_rating" field.
func (_u *BookFeedbackUpdate) AddDifficultyRating(v int) *BookFeedbackUpdate {
	_u.mutation.AddDifficultyRating(v)
	return _u
}

// ClearDifficultyRating clears the value of the "difficulty_rating" field.
func (_u *BookFeedbackUpdate) ClearDifficultyRating() *BookFeedbackUpdate {
	_u.mutation.ClearDifficultyRating()
	return _u
}

// SetUseScenario sets the "use_scenario" field.
func (_u *BookFeedbackUpdate) SetUseScenario(v string) *BookFeedbackUpdate {
	_u.mutation.SetUseScenario(v)
	return _u
}

// SetNillableUseScenario sets the "use_scenario" field if the given value is not nil.
func (_u *BookFeedbackUpdate) SetNillableUseScenario(v *string) *BookFeedbackUpdate {
	if v != nil {
		_u.SetUseScenario(*v)
	}
	return _u
}

// ClearUseScenario clears the value of the "use_scenario" field.
func (_u *BookFeedbackUpdate) ClearUseScenario() *BookFeedbackUpdate {
	_u.mutation.ClearUseScenario()
	return _u
}

// AddUserIDs adds the "user" edge to the User entity by IDs.
func (_u *BookFeedbackUpdate) AddUserIDs(ids ...uuid.UUID) *BookFeedbackUpdate {
	_u.mutation.AddUserIDs(ids...)
	return _u
}

// AddUser adds the "user" edges to the User entity.
func (_u *BookFeedbackUpdate) AddUser(v ...*User) *BookFeedbackUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddUserIDs(ids...)
}

// AddBookIDs adds the "book" edge to the Book entity by IDs.
func (_u *BookFeedbackUpdate) AddBookIDs(ids ...uuid.UUID) *BookFeedbackUpdate {
	_u.mutation.AddBookIDs(ids...)
	return _u
}

// AddBook adds the "book" edges to the Book entity.
func (_u *BookFeedbackUpdate) AddBook(v ...*Book) *BookFeedbackUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddBookIDs(ids...)
}

// Mutation returns the BookFeedbackMutation object of the builder.
func (_u *BookFeedbackUpdate) Mutation() *BookFeedbackMutation {
	return _u.mutation
}

// ClearUser clears all "user" edges to the User entity.
func (_u *BookFeedbackUpdate) ClearUser() *BookFeedbackUpdate {
	_u.mutation.ClearUser()
	return _u
}

// RemoveUserIDs removes the "user" edge to User entities by IDs.
func (_u *BookFeedbackUpdate) RemoveUserIDs(ids ...uuid.UUID) *BookFeedbackUpdate {
	_u.mutation.RemoveUserIDs(ids...)
	return _u
}

// RemoveUser removes "user" edges to User entities.
func (_u *BookFeedbackUpdate) RemoveUser(v ...*User) *BookFeedbackUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveUserIDs(ids...)
}

// ClearBook clears all "book" edges to the Book entity.
func (_u *BookFeedbackUpdate) ClearBook() *BookFeedbackUpdate {
	_u.mutation.ClearBook()
	return _u
}

// RemoveBookIDs removes the "book" edge to Book entities by IDs.
func (_u *BookFeedbackUpdate) RemoveBookIDs(ids ...uuid.UUID) *BookFeedbackUpdate {
	_u.mutation.RemoveBookIDs(ids...)
	return _u
}

// RemoveBook removes "book" edges to Book entities.
func (_u *BookFeedbackUpdate) RemoveBook(v ...*Book) *BookFeedbackUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveBookIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *BookFeedbackUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *BookFeedbackUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *BookFeedbackUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *BookFeedbackUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *BookFeedbackUpdate) check() error {
	if v, ok := _u.mutation.FeedbackType(); ok {
		if err := bookfeedback.FeedbackTypeValidator(v); err != nil {
			return &ValidationError{Name: "feedback_type", err: fmt.Errorf(`ent: validator failed for field "BookFeedback.feedback_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.UseScenario(); ok {
		if err := bookfeedback.UseScenarioValidator(v); err != nil {
			return &ValidationError{Name: "use_scenario", err: fmt.Errorf(`ent: validator failed for field "BookFeedback.use_scenario": %w`, err)}
		}
	}
	return nil
}

func (_u *BookFeedbackUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(bookfeedback.Table, bookfeedback.Columns, sqlgraph.NewFieldSpec(bookfeedback.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UserID(); ok {
		_spec.SetField(bookfeedback.FieldUserID, field.TypeUUID, value)
	}
	if value, ok := _u.mutation.BookID(); ok {
		_spec.SetField(bookfeedback.FieldBookID, field.TypeUUID, value)
	}
	if value, ok := _u.mutation.FeedbackType(); ok {
		_spec.SetField(bookfeedback.FieldFeedbackType, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.DifficultyRating(); ok {
		_spec.SetField(bookfeedback.FieldDifficultyRating, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedDifficultyRating(); ok {
		_spec.AddField(bookfeedback.FieldDifficultyRating, field.TypeInt, value)
	}
	if _u.mutation.DifficultyRatingCleared() {
		_spec.ClearField(bookfeedback.FieldDifficultyRating, field.TypeInt)
	}
	if value, ok := _u.mutation.UseScenario(); ok {
		_spec.SetField(bookfeedback.FieldUseScenario, field.TypeString, value)
	}
	if _u.mutation.UseScenarioCleared() {
		_spec.ClearField(bookfeedback.FieldUseScenario, field.TypeString)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   bookfeedback.UserTable,
			Columns: []string{bookfeedback.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedUserIDs(); len(nodes) > 0 && !_u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   bookfeedback.UserTable,
			Columns: []string{bookfeedback.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   bookfeedback.UserTable,
			Columns: []string{bookfeedback.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.BookCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   bookfeedback.BookTable,
			Columns: []string{bookfeedback.BookColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(book.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedBookIDs(); len(nodes) > 0 && !_u.mutation.BookCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   bookfeedback.BookTable,
			Columns: []string{bookfeedback.BookColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(book.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.BookIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   bookfeedback.BookTable,
			Columns: []string{bookfeedback.BookColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(book.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{bookfeedback.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// BookFeedbackUpdateOne is the builder for updating a single BookFeedback entity.
type BookFeedbackUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *BookFeedbackMutation
}

// SetUserID sets the "user_id" field.
func (_u *BookFeedbackUpdateOne) SetUserID(v uuid.UUID) *BookFeedbackUpdateOne {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *BookFeedbackUpdateOne) SetNillableUserID(v *uuid.UUID) *BookFeedbackUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetBookID sets the "book_id" field.
func (_u *BookFeedbackUpdateOne) SetBookID(v uuid.UUID) *BookFeedbackUpdateOne {
	_u.mutation.SetBookID(v)
	return _u
}

// SetNillableBookID sets the "book_id" field if the given value is not nil.
func (_u *BookFeedbackUpdateOne) SetNillableBookID(v *uuid.UUID) *BookFeedbackUpdateOne {
	if v != nil {
		_u.SetBookID(*v)
	}
	return _u
}

// SetFeedbackType sets the "feedback_type" field.
func (_u *BookFeedbackUpdateOne) SetFeedbackType(v bookfeedback.FeedbackType) *BookFeedbackUpdateOne {
	_u.mutation.SetFeedbackType(v)
	return _u
}

// SetNillableFeedbackType sets the "feedback_type" field if the given value is not nil.
func (_u *BookFeedbackUpdateOne) SetNillableFeedbackType(v *bookfeedback.FeedbackType) *BookFeedbackUpdateOne {
	if v != nil {
		_u.SetFeedbackType(*v)
	}
	return _u
}

// SetDifficultyRating sets the "difficulty_rating" field.
func (_u *BookFeedbackUpdateOne) SetDifficultyRating(v int) *BookFeedbackUpdateOne {
	_u.mutation.ResetDifficultyRating()
	_u.mutation.SetDifficultyRating(v)
	return _u
}

// SetNillableDifficultyRating sets the "difficulty_rating" field if the given value is not nil.
func (_u *BookFeedbackUpdateOne) SetNillableDifficultyRating(v *int) *BookFeedbackUpdateOne {
	if v != nil {
		_u.SetDifficultyRating(*v)
	}
	return _u
}

// AddDifficultyRating adds value to the "difficulty_rating" field.
func (_u *BookFeedbackUpdateOne) AddDifficultyRating(v int) *BookFeedbackUpdateOne {
	_u.mutation.AddDifficultyRating(v)
	return _u
}

// ClearDifficultyRating clears the value of the "difficulty_rating" field.
func (_u *BookFeedbackUpdateOne) ClearDifficultyRating() *BookFeedbackUpdateOne {
	_u.mutation.ClearDifficultyRating()
	return _u
}

// SetUseScenario sets the "use_scenario" field.
func (_u *BookFeedbackUpdateOne) SetUseScenario(v string) *BookFeedbackUpdateOne {
	_u.mutation.SetUseScenario(v)
	return _u
}

// SetNillableUseScenario sets the "use_scenario" field if the given value is not nil.
func (_u *BookFeedbackUpdateOne) SetNillableUseScenario(v *string) *BookFeedbackUpdateOne {
	if v != nil {
		_u.SetUseScenario(*v)
	}
	return _u
}

// ClearUseScenario clears the value of the "use_scenario" field.
func (_u *BookFeedbackUpdateOne) ClearUseScenario() *BookFeedbackUpdateOne {
	_u.mutation.ClearUseScenario()
	return _u
}

// AddUserIDs adds the "user" edge to the User entity by IDs.
func (_u *BookFeedbackUpdateOne) AddUserIDs(ids ...uuid.UUID) *BookFeedbackUpdateOne {
	_u.mutation.AddUserIDs(ids...)
	return _u
}

// AddUser adds the "user" edges to the User entity.
func (_u *BookFeedbackUpdateOne) AddUser(v ...*User) *BookFeedbackUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddUserIDs(ids...)
}

// AddBookIDs adds the "book" edge to the Book entity by IDs.
func (_u *BookFeedbackUpdateOne) AddBookIDs(ids ...uuid.UUID) *BookFeedbackUpdateOne {
	_u.mutation.AddBookIDs(ids...)
	return _u
}

// AddBook adds the "book" edges to the Book entity.
func (_u *BookFeedbackUpdateOne) AddBook(v ...*Book) *BookFeedbackUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddBookIDs(ids...)
}

// Mutation returns the BookFeedbackMutation object of the builder.
func (_u *BookFeedbackUpdateOne) Mutation() *BookFeedbackMutation {
	return _u.mutation
}

// ClearUser clears all "user" edges to the User entity.
func (_u *BookFeedbackUpdateOne) ClearUser() *BookFeedbackUpdateOne {
	_u.mutation.ClearUser()
	return _u
}

// RemoveUserIDs removes the "user" edge to User entities by IDs.
func (_u *BookFeedbackUpdateOne) RemoveUserIDs(ids ...uuid.UUID) *BookFeedbackUpdateOne {
	_u.mutation.RemoveUserIDs(ids...)
	return _u
}

// RemoveUser removes "user" edges to User entities.
func (_u *BookFeedbackUpdateOne) RemoveUser(v ...*User) *BookFeedbackUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveUserIDs(ids...)
}

// ClearBook clears all "book" edges to the Book entity.
func (_u *BookFeedbackUpdateOne) ClearBook() *BookFeedbackUpdateOne {
	_u.mutation.ClearBook()
	return _u
}

// RemoveBookIDs removes the "book" edge to Book entities by IDs.
func (_u *BookFeedbackUpdateOne) RemoveBookIDs(ids ...uuid.UUID) *BookFeedbackUpdateOne {
	_u.mutation.RemoveBookIDs(ids...)
	return _u
}

// RemoveBook removes "book" edges to Book entities.
func (_u *BookFeedbackUpdateOne) RemoveBook(v ...*Book) *BookFeedbackUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveBookIDs(ids...)
}

// Where appends a list predicates to the BookFeedbackUpdate builder.
func (_u *BookFeedbackUpdateOne) Where(ps ...predicate.BookFeedback) *BookFeedbackUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *BookFeedbackUpdateOne) Select(field string, fields ...string) *BookFeedbackUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated BookFeedback entity.
func (_u *BookFeedbackUpdateOne) Save(ctx context.Context) (*BookFeedback, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *BookFeedbackUpdateOne) SaveX(ctx context.Context) *BookFeedback {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *BookFeedbackUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *BookFeedbackUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *BookFeedbackUpdateOne) check() error {
	if v, ok := _u.mutation.FeedbackType(); ok {
		if err := bookfeedback.FeedbackTypeValidator(v); err != nil {
			return &ValidationError{Name: "feedback_type", err: fmt.Errorf(`ent: validator failed for field "BookFeedback.feedback_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.UseScenario(); ok {
		if err := bookfeedback.UseScenarioValidator(v); err != nil {
			return &ValidationError{Name: "use_scenario", err: fmt.Errorf(`ent: validator failed for field "BookFeedback.use_scenario": %w`, err)}
		}
	}
	return nil
}

func (_u *BookFeedbackUpdateOne) sqlSave(ctx context.Context) (_node *BookFeedback, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(bookfeedback.Table, bookfeedback.Columns, sqlgraph.NewFieldSpec(bookfeedback.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "BookFeedback.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, bookfeedback.FieldID)
		for _, f := range fields {
			if !bookfeedback.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != bookfeedback.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UserID(); ok {
		_spec.SetField(bookfeedback.FieldUserID, field.TypeUUID, value)
	}
	if value, ok := _u.mutation.BookID(); ok {
		_spec.SetField(bookfeedback.FieldBookID, field.TypeUUID, value)
	}
	if value, ok := _u.mutation.FeedbackType(); ok {
		_spec.SetField(bookfeedback.FieldFeedbackType, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.DifficultyRating(); ok {
		_spec.SetField(bookfeedback.FieldDifficultyRating, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedDifficultyRating(); ok {
		_spec.AddField(bookfeedback.FieldDifficultyRating, field.TypeInt, value)
	}
	if _u.mutation.DifficultyRatingCleared() {
		_spec.ClearField(bookfeedback.FieldDifficultyRating, field.TypeInt)
	}
	if value, ok := _u.mutation.UseScenario(); ok {
		_spec.SetField(bookfeedback.FieldUseScenario, field.TypeString, value)
	}
	if _u.mutation.UseScenarioCleared() {
		_spec.ClearField(bookfeedback.FieldUseScenario, field.TypeString)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   bookfeedback.UserTable,
			Columns: []string{bookfeedback.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedUserIDs(); len(nodes) > 0 && !_u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   bookfeedback.UserTable,
			Columns: []string{bookfeedback.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   bookfeedback.UserTable,
			Columns: []string{bookfeedback.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.BookCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   bookfeedback.BookTable,
			Columns: []string{bookfeedback.BookColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(book.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedBookIDs(); len(nodes) > 0 && !_u.mutation.BookCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   bookfeedback.BookTable,
			Columns: []string{bookfeedback.BookColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(book.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.BookIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   bookfeedback.BookTable,
			Columns: []string{bookfeedback.BookColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(book.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &BookFeedback{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{bookfeedback.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
