// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"database/sql/driver"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/zhoumingjun/bookmgr/backend/ent/book"
	"github.com/zhoumingjun/bookmgr/backend/ent/bookfeedback"
	"github.com/zhoumingjun/bookmgr/backend/ent/predicate"
	"github.com/zhoumingjun/bookmgr/backend/ent/user"
)

// BookFeedbackQuery is the builder for querying BookFeedback entities.
type BookFeedbackQuery struct {
	config
	ctx        *QueryContext
	order      []bookfeedback.OrderOption
	inters     []Interceptor
	predicates []predicate.BookFeedback
	withUser   *UserQuery
	withBook   *BookQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the BookFeedbackQuery builder.
func (_q *BookFeedbackQuery) Where(ps ...predicate.BookFeedback) *BookFeedbackQuery {
	_q.predicates = append(_q.predicates, ps...)
	return _q
}

// Limit the number of records to be returned by this query.
func (_q *BookFeedbackQuery) Limit(limit int) *BookFeedbackQuery {
	_q.ctx.Limit = &limit
	return _q
}

// Offset to start from.
func (_q *BookFeedbackQuery) Offset(offset int) *BookFeedbackQuery {
	_q.ctx.Offset = &offset
	return _q
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (_q *BookFeedbackQuery) Unique(unique bool) *BookFeedbackQuery {
	_q.ctx.Unique = &unique
	return _q
}

// Order specifies how the records should be ordered.
func (_q *BookFeedbackQuery) Order(o ...bookfeedback.OrderOption) *BookFeedbackQuery {
	_q.order = append(_q.order, o...)
	return _q
}

// QueryUser chains the current query on the "user" edge.
func (_q *BookFeedbackQuery) QueryUser() *UserQuery {
	query := (&UserClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(bookfeedback.Table, bookfeedback.FieldID, selector),
			sqlgraph.To(user.Table, user.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, bookfeedback.UserTable, bookfeedback.UserColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryBook chains the current query on the "book" edge.
func (_q *BookFeedbackQuery) QueryBook() *BookQuery {
	query := (&BookClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(bookfeedback.Table, bookfeedback.FieldID, selector),
			sqlgraph.To(book.Table, book.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, bookfeedback.BookTable, bookfeedback.BookColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first BookFeedback entity from the query.
// Returns a *NotFoundError when no BookFeedback was found.
func (_q *BookFeedbackQuery) First(ctx context.Context) (*BookFeedback, error) {
	nodes, err := _q.Limit(1).All(setContextOp(ctx, _q.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{bookfeedback.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (_q *BookFeedbackQuery) FirstX(ctx context.Context) *BookFeedback {
	node, err := _q.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first BookFeedback ID from the query.
// Returns a *NotFoundError when no BookFeedback ID was found.
func (_q *BookFeedbackQuery) FirstID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = _q.Limit(1).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{bookfeedback.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (_q *BookFeedbackQuery) FirstIDX(ctx context.Context) uuid.UUID {
	id, err := _q.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single BookFeedback entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one BookFeedback entity is found.
// Returns a *NotFoundError when no BookFeedback entities are found.
func (_q *BookFeedbackQuery) Only(ctx context.Context) (*BookFeedback, error) {
	nodes, err := _q.Limit(2).All(setContextOp(ctx, _q.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{bookfeedback.Label}
	default:
		return nil, &NotSingularError{bookfeedback.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (_q *BookFeedbackQuery) OnlyX(ctx context.Context) *BookFeedback {
	node, err := _q.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only BookFeedback ID in the query.
// Returns a *NotSingularError when more than one BookFeedback ID is found.
// Returns a *NotFoundError when no entities are found.
func (_q *BookFeedbackQuery) OnlyID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = _q.Limit(2).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{bookfeedback.Label}
	default:
		err = &NotSingularError{bookfeedback.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (_q *BookFeedbackQuery) OnlyIDX(ctx context.Context) uuid.UUID {
	id, err := _q.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of BookFeedbacks.
func (_q *BookFeedbackQuery) All(ctx context.Context) ([]*BookFeedback, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryAll)
	if err := _q.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*BookFeedback, *BookFeedbackQuery]()
	return withInterceptors[[]*BookFeedback](ctx, _q, qr, _q.inters)
}

// AllX is like All, but panics if an error occurs.
func (_q *BookFeedbackQuery) AllX(ctx context.Context) []*BookFeedback {
	nodes, err := _q.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of BookFeedback IDs.
func (_q *BookFeedbackQuery) IDs(ctx context.Context) (ids []uuid.UUID, err error) {
	if _q.ctx.Unique == nil && _q.path != nil {
		_q.Unique(true)
	}
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryIDs)
	if err = _q.Select(bookfeedback.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (_q *BookFeedbackQuery) IDsX(ctx context.Context) []uuid.UUID {
	ids, err := _q.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (_q *BookFeedbackQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryCount)
	if err := _q.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, _q, querierCount[*BookFeedbackQuery](), _q.inters)
}

// CountX is like Count, but panics if an error occurs.
func (_q *BookFeedbackQuery) CountX(ctx context.Context) int {
	count, err := _q.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (_q *BookFeedbackQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryExist)
	switch _, err := _q.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (_q *BookFeedbackQuery) ExistX(ctx context.Context) bool {
	exist, err := _q.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the BookFeedbackQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (_q *BookFeedbackQuery) Clone() *BookFeedbackQuery {
	if _q == nil {
		return nil
	}
	return &BookFeedbackQuery{
		config:     _q.config,
		ctx:        _q.ctx.Clone(),
		order:      append([]bookfeedback.OrderOption{}, _q.order...),
		inters:     append([]Interceptor{}, _q.inters...),
		predicates: append([]predicate.BookFeedback{}, _q.predicates...),
		withUser:   _q.withUser.Clone(),
		withBook:   _q.withBook.Clone(),
		// clone intermediate query.
		sql:  _q.sql.Clone(),
		path: _q.path,
	}
}

// WithUser tells the query-builder to eager-load the nodes that are connected to
// the "user" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *BookFeedbackQuery) WithUser(opts ...func(*UserQuery)) *BookFeedbackQuery {
	query := (&UserClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withUser = query
	return _q
}

// WithBook tells the query-builder to eager-load the nodes that are connected to
// the "book" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *BookFeedbackQuery) WithBook(opts ...func(*BookQuery)) *BookFeedbackQuery {
	query := (&BookClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withBook = query
	return _q
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		UserID uuid.UUID `json:"user_id,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.BookFeedback.Query().
//		GroupBy(bookfeedback.FieldUserID).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (_q *BookFeedbackQuery) GroupBy(field string, fields ...string) *BookFeedbackGroupBy {
	_q.ctx.Fields = append([]string{field}, fields...)
	grbuild := &BookFeedbackGroupBy{build: _q}
	grbuild.flds = &_q.ctx.Fields
	grbuild.label = bookfeedback.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		UserID uuid.UUID `json:"user_id,omitempty"`
//	}
//
//	client.BookFeedback.Query().
//		Select(bookfeedback.FieldUserID).
//		Scan(ctx, &v)
func (_q *BookFeedbackQuery) Select(fields ...string) *BookFeedbackSelect {
	_q.ctx.Fields = append(_q.ctx.Fields, fields...)
	sbuild := &BookFeedbackSelect{BookFeedbackQuery: _q}
	sbuild.label = bookfeedback.Label
	sbuild.flds, sbuild.scan = &_q.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a BookFeedbackSelect configured with the given aggregations.
func (_q *BookFeedbackQuery) Aggregate(fns ...AggregateFunc) *BookFeedbackSelect {
	return _q.Select().Aggregate(fns...)
}

func (_q *BookFeedbackQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range _q.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, _q); err != nil {
				return err
			}
		}
	}
	for _, f := range _q.ctx.Fields {
		if !bookfeedback.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if _q.path != nil {
		prev, err := _q.path(ctx)
		if err != nil {
			return err
		}
		_q.sql = prev
	}
	return nil
}

func (_q *BookFeedbackQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*BookFeedback, error) {
	var (
		nodes       = []*BookFeedback{}
		_spec       = _q.querySpec()
		loadedTypes = [2]bool{
			_q.withUser != nil,
			_q.withBook != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*BookFeedback).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &BookFeedback{config: _q.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, _q.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := _q.withUser; query != nil {
		if err := _q.loadUser(ctx, query, nodes,
			func(n *BookFeedback) { n.Edges.User = []*User{} },
			func(n *BookFeedback, e *User) { n.Edges.User = append(n.Edges.User, e) }); err != nil {
			return nil, err
		}
	}
	if query := _q.withBook; query != nil {
		if err := _q.loadBook(ctx, query, nodes,
			func(n *BookFeedback) { n.Edges.Book = []*Book{} },
			func(n *BookFeedback, e *Book) { n.Edges.Book = append(n.Edges.Book, e) }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (_q *BookFeedbackQuery) loadUser(ctx context.Context, query *UserQuery, nodes []*BookFeedback, init func(*BookFeedback), assign func(*BookFeedback, *User)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[uuid.UUID]*BookFeedback)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	query.withFKs = true
	query.Where(predicate.User(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(bookfeedback.UserColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.book_feedback_user
		if fk == nil {
			return fmt.Errorf(`foreign-key "book_feedback_user" is nil for node %v`, n.ID)
		}
		node, ok := nodeids[*fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "book_feedback_user" returned %v for node %v`, *fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}
func (_q *BookFeedbackQuery) loadBook(ctx context.Context, query *BookQuery, nodes []*BookFeedback, init func(*BookFeedback), assign func(*BookFeedback, *Book)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[uuid.UUID]*BookFeedback)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	query.withFKs = true
	query.Where(predicate.Book(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(bookfeedback.BookColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.book_feedback_book
		if fk == nil {
			return fmt.Errorf(`foreign-key "book_feedback_book" is nil for node %v`, n.ID)
		}
		node, ok := nodeids[*fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "book_feedback_book" returned %v for node %v`, *fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}

func (_q *BookFeedbackQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := _q.querySpec()
	_spec.Node.Columns = _q.ctx.Fields
	if len(_q.ctx.Fields) > 0 {
		_spec.Unique = _q.ctx.Unique != nil && *_q.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, _q.driver, _spec)
}

func (_q *BookFeedbackQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(bookfeedback.Table, bookfeedback.Columns, sqlgraph.NewFieldSpec(bookfeedback.FieldID, field.TypeUUID))
	_spec.From = _q.sql
	if unique := _q.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if _q.path != nil {
		_spec.Unique = true
	}
	if fields := _q.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, bookfeedback.FieldID)
		for i := range fields {
			if fields[i] != bookfeedback.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := _q.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := _q.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := _q.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := _q.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (_q *BookFeedbackQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(_q.driver.Dialect())
	t1 := builder.Table(bookfeedback.Table)
	columns := _q.ctx.Fields
	if len(columns) == 0 {
		columns = bookfeedback.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if _q.sql != nil {
		selector = _q.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if _q.ctx.Unique != nil && *_q.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range _q.predicates {
		p(selector)
	}
	for _, p := range _q.order {
		p(selector)
	}
	if offset := _q.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := _q.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// BookFeedbackGroupBy is the group-by builder for BookFeedback entities.
type BookFeedbackGroupBy struct {
	selector
	build *BookFeedbackQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (_g *BookFeedbackGroupBy) Aggregate(fns ...AggregateFunc) *BookFeedbackGroupBy {
	_g.fns = append(_g.fns, fns...)
	return _g
}

// Scan applies the selector query and scans the result into the given value.
func (_g *BookFeedbackGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _g.build.ctx, ent.OpQueryGroupBy)
	if err := _g.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*BookFeedbackQuery, *BookFeedbackGroupBy](ctx, _g.build, _g, _g.build.inters, v)
}

func (_g *BookFeedbackGroupBy) sqlScan(ctx context.Context, root *BookFeedbackQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(_g.fns))
	for _, fn := range _g.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*_g.flds)+len(_g.fns))
		for _, f := range *_g.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*_g.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _g.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// BookFeedbackSelect is the builder for selecting fields of BookFeedback entities.
type BookFeedbackSelect struct {
	*BookFeedbackQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (_s *BookFeedbackSelect) Aggregate(fns ...AggregateFunc) *BookFeedbackSelect {
	_s.fns = append(_s.fns, fns...)
	return _s
}

// Scan applies the selector query and scans the result into the given value.
func (_s *BookFeedbackSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _s.ctx, ent.OpQuerySelect)
	if err := _s.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*BookFeedbackQuery, *BookFeedbackSelect](ctx, _s.BookFeedbackQuery, _s, _s.inters, v)
}

func (_s *BookFeedbackSelect) sqlScan(ctx context.Context, root *BookFeedbackQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(_s.fns))
	for _, fn := range _s.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*_s.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _s.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
