// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/zhoumingjun/bookmgr/backend/ent/bookfeedback"
	"github.com/zhoumingjun/bookmgr/backend/ent/predicate"
)

// BookFeedbackDelete is the builder for deleting a BookFeedback entity.
type BookFeedbackDelete struct {
	config
	hooks    []Hook
	mutation *BookFeedbackMutation
}

// Where appends a list predicates to the BookFeedbackDelete builder.
func (_d *BookFeedbackDelete) Where(ps ...predicate.BookFeedback) *BookFeedbackDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *BookFeedbackDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *BookFeedbackDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *BookFeedbackDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(bookfeedback.Table, sqlgraph.NewFieldSpec(bookfeedback.FieldID, field.TypeUUID))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// BookFeedbackDeleteOne is the builder for deleting a single BookFeedback entity.
type BookFeedbackDeleteOne struct {
	_d *BookFeedbackDelete
}

// Where appends a list predicates to the BookFeedbackDelete builder.
func (_d *BookFeedbackDeleteOne) Where(ps ...predicate.BookFeedback) *BookFeedbackDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *BookFeedbackDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{bookfeedback.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *BookFeedbackDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
