// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"log"
	"reflect"

	"github.com/google/uuid"
	"github.com/zhoumingjun/bookmgr/backend/ent/migrate"

	"entgo.io/ent"
	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/zhoumingjun/bookmgr/backend/ent/book"
	"github.com/zhoumingjun/bookmgr/backend/ent/bookdimension"
	"github.com/zhoumingjun/bookmgr/backend/ent/bookfile"
	"github.com/zhoumingjun/bookmgr/backend/ent/bookreadingprogress"
	"github.com/zhoumingjun/bookmgr/backend/ent/bookreview"
	"github.com/zhoumingjun/bookmgr/backend/ent/booksearchindex"
	"github.com/zhoumingjun/bookmgr/backend/ent/dimension"
	"github.com/zhoumingjun/bookmgr/backend/ent/user"
)

// Client is the client that holds all ent builders.
type Client struct {
	config
	// Schema is the client for creating, migrating and dropping schema.
	Schema *migrate.Schema
	// Book is the client for interacting with the Book builders.
	Book *BookClient
	// BookDimension is the client for interacting with the BookDimension builders.
	BookDimension *BookDimensionClient
	// BookFile is the client for interacting with the BookFile builders.
	BookFile *BookFileClient
	// BookReadingProgress is the client for interacting with the BookReadingProgress builders.
	BookReadingProgress *BookReadingProgressClient
	// BookReview is the client for interacting with the BookReview builders.
	BookReview *BookReviewClient
	// BookSearchIndex is the client for interacting with the BookSearchIndex builders.
	BookSearchIndex *BookSearchIndexClient
	// Dimension is the client for interacting with the Dimension builders.
	Dimension *DimensionClient
	// User is the client for interacting with the User builders.
	User *UserClient
}

// NewClient creates a new client configured with the given options.
func NewClient(opts ...Option) *Client {
	client := &Client{config: newConfig(opts...)}
	client.init()
	return client
}

func (c *Client) init() {
	c.Schema = migrate.NewSchema(c.driver)
	c.Book = NewBookClient(c.config)
	c.BookDimension = NewBookDimensionClient(c.config)
	c.BookFile = NewBookFileClient(c.config)
	c.BookReadingProgress = NewBookReadingProgressClient(c.config)
	c.BookReview = NewBookReviewClient(c.config)
	c.BookSearchIndex = NewBookSearchIndexClient(c.config)
	c.Dimension = NewDimensionClient(c.config)
	c.User = NewUserClient(c.config)
}

type (
	// config is the configuration for the client and its builder.
	config struct {
		// driver used for executing database requests.
		driver dialect.Driver
		// debug enable a debug logging.
		debug bool
		// log used for logging on debug mode.
		log func(...any)
		// hooks to execute on mutations.
		hooks *hooks
		// interceptors to execute on queries.
		inters *inters
	}
	// Option function to configure the client.
	Option func(*config)
)

// newConfig creates a new config for the client.
func newConfig(opts ...Option) config {
	cfg := config{log: log.Println, hooks: &hooks{}, inters: &inters{}}
	cfg.options(opts...)
	return cfg
}

// options applies the options on the config object.
func (c *config) options(opts ...Option) {
	for _, opt := range opts {
		opt(c)
	}
	if c.debug {
		c.driver = dialect.Debug(c.driver, c.log)
	}
}

// Debug enables debug logging on the ent.Driver.
func Debug() Option {
	return func(c *config) {
		c.debug = true
	}
}

// Log sets the logging function for debug mode.
func Log(fn func(...any)) Option {
	return func(c *config) {
		c.log = fn
	}
}

// Driver configures the client driver.
func Driver(driver dialect.Driver) Option {
	return func(c *config) {
		c.driver = driver
	}
}

// Open opens a database/sql.DB specified by the driver name and
// the data source name, and returns a new client attached to it.
// Optional parameters can be added for configuring the client.
func Open(driverName, dataSourceName string, options ...Option) (*Client, error) {
	switch driverName {
	case dialect.MySQL, dialect.Postgres, dialect.SQLite:
		drv, err := sql.Open(driverName, dataSourceName)
		if err != nil {
			return nil, err
		}
		return NewClient(append(options, Driver(drv))...), nil
	default:
		return nil, fmt.Errorf("unsupported driver: %q", driverName)
	}
}

// ErrTxStarted is returned when trying to start a new transaction from a transactional client.
var ErrTxStarted = errors.New("ent: cannot start a transaction within a transaction")

// Tx returns a new transactional client. The provided context
// is used until the transaction is committed or rolled back.
func (c *Client) Tx(ctx context.Context) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, ErrTxStarted
	}
	tx, err := newTx(ctx, c.driver)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = tx
	return &Tx{
		ctx:                 ctx,
		config:              cfg,
		Book:                NewBookClient(cfg),
		BookDimension:       NewBookDimensionClient(cfg),
		BookFile:            NewBookFileClient(cfg),
		BookReadingProgress: NewBookReadingProgressClient(cfg),
		BookReview:          NewBookReviewClient(cfg),
		BookSearchIndex:     NewBookSearchIndexClient(cfg),
		Dimension:           NewDimensionClient(cfg),
		User:                NewUserClient(cfg),
	}, nil
}

// BeginTx returns a transactional client with specified options.
func (c *Client) BeginTx(ctx context.Context, opts *sql.TxOptions) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, errors.New("ent: cannot start a transaction within a transaction")
	}
	tx, err := c.driver.(interface {
		BeginTx(context.Context, *sql.TxOptions) (dialect.Tx, error)
	}).BeginTx(ctx, opts)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = &txDriver{tx: tx, drv: c.driver}
	return &Tx{
		ctx:                 ctx,
		config:              cfg,
		Book:                NewBookClient(cfg),
		BookDimension:       NewBookDimensionClient(cfg),
		BookFile:            NewBookFileClient(cfg),
		BookReadingProgress: NewBookReadingProgressClient(cfg),
		BookReview:          NewBookReviewClient(cfg),
		BookSearchIndex:     NewBookSearchIndexClient(cfg),
		Dimension:           NewDimensionClient(cfg),
		User:                NewUserClient(cfg),
	}, nil
}

// Debug returns a new debug-client. It's used to get verbose logging on specific operations.
//
//	client.Debug().
//		Book.
//		Query().
//		Count(ctx)
func (c *Client) Debug() *Client {
	if c.debug {
		return c
	}
	cfg := c.config
	cfg.driver = dialect.Debug(c.driver, c.log)
	client := &Client{config: cfg}
	client.init()
	return client
}

// Close closes the database connection and prevents new queries from starting.
func (c *Client) Close() error {
	return c.driver.Close()
}

// Use adds the mutation hooks to all the entity clients.
// In order to add hooks to a specific client, call: `client.Node.Use(...)`.
func (c *Client) Use(hooks ...Hook) {
	for _, n := range []interface{ Use(...Hook) }{
		c.Book, c.BookDimension, c.BookFile, c.BookReadingProgress, c.BookReview,
		c.BookSearchIndex, c.Dimension, c.User,
	} {
		n.Use(hooks...)
	}
}

// Intercept adds the query interceptors to all the entity clients.
// In order to add interceptors to a specific client, call: `client.Node.Intercept(...)`.
func (c *Client) Intercept(interceptors ...Interceptor) {
	for _, n := range []interface{ Intercept(...Interceptor) }{
		c.Book, c.BookDimension, c.BookFile, c.BookReadingProgress, c.BookReview,
		c.BookSearchIndex, c.Dimension, c.User,
	} {
		n.Intercept(interceptors...)
	}
}

// Mutate implements the ent.Mutator interface.
func (c *Client) Mutate(ctx context.Context, m Mutation) (Value, error) {
	switch m := m.(type) {
	case *BookMutation:
		return c.Book.mutate(ctx, m)
	case *BookDimensionMutation:
		return c.BookDimension.mutate(ctx, m)
	case *BookFileMutation:
		return c.BookFile.mutate(ctx, m)
	case *BookReadingProgressMutation:
		return c.BookReadingProgress.mutate(ctx, m)
	case *BookReviewMutation:
		return c.BookReview.mutate(ctx, m)
	case *BookSearchIndexMutation:
		return c.BookSearchIndex.mutate(ctx, m)
	case *DimensionMutation:
		return c.Dimension.mutate(ctx, m)
	case *UserMutation:
		return c.User.mutate(ctx, m)
	default:
		return nil, fmt.Errorf("ent: unknown mutation type %T", m)
	}
}

// BookClient is a client for the Book schema.
type BookClient struct {
	config
}

// NewBookClient returns a client for the Book from the given config.
func NewBookClient(c config) *BookClient {
	return &BookClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `book.Hooks(f(g(h())))`.
func (c *BookClient) Use(hooks ...Hook) {
	c.hooks.Book = append(c.hooks.Book, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `book.Intercept(f(g(h())))`.
func (c *BookClient) Intercept(interceptors ...Interceptor) {
	c.inters.Book = append(c.inters.Book, interceptors...)
}

// Create returns a builder for creating a Book entity.
func (c *BookClient) Create() *BookCreate {
	mutation := newBookMutation(c.config, OpCreate)
	return &BookCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of Book entities.
func (c *BookClient) CreateBulk(builders ...*BookCreate) *BookCreateBulk {
	return &BookCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *BookClient) MapCreateBulk(slice any, setFunc func(*BookCreate, int)) *BookCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &BookCreateBulk{err: fmt.Errorf("calling to BookClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*BookCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &BookCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for Book.
func (c *BookClient) Update() *BookUpdate {
	mutation := newBookMutation(c.config, OpUpdate)
	return &BookUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *BookClient) UpdateOne(_m *Book) *BookUpdateOne {
	mutation := newBookMutation(c.config, OpUpdateOne, withBook(_m))
	return &BookUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *BookClient) UpdateOneID(id uuid.UUID) *BookUpdateOne {
	mutation := newBookMutation(c.config, OpUpdateOne, withBookID(id))
	return &BookUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for Book.
func (c *BookClient) Delete() *BookDelete {
	mutation := newBookMutation(c.config, OpDelete)
	return &BookDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *BookClient) DeleteOne(_m *Book) *BookDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *BookClient) DeleteOneID(id uuid.UUID) *BookDeleteOne {
	builder := c.Delete().Where(book.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &BookDeleteOne{builder}
}

// Query returns a query builder for Book.
func (c *BookClient) Query() *BookQuery {
	return &BookQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeBook},
		inters: c.Interceptors(),
	}
}

// Get returns a Book entity by its id.
func (c *BookClient) Get(ctx context.Context, id uuid.UUID) (*Book, error) {
	return c.Query().Where(book.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *BookClient) GetX(ctx context.Context, id uuid.UUID) *Book {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryUploader queries the uploader edge of a Book.
func (c *BookClient) QueryUploader(_m *Book) *UserQuery {
	query := (&UserClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(book.Table, book.FieldID, id),
			sqlgraph.To(user.Table, user.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, book.UploaderTable, book.UploaderColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QueryBookDimensions queries the book_dimensions edge of a Book.
func (c *BookClient) QueryBookDimensions(_m *Book) *BookDimensionQuery {
	query := (&BookDimensionClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(book.Table, book.FieldID, id),
			sqlgraph.To(bookdimension.Table, bookdimension.FieldID),
			sqlgraph.Edge(sqlgraph.M2M, false, book.BookDimensionsTable, book.BookDimensionsPrimaryKey...),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QueryFiles queries the files edge of a Book.
func (c *BookClient) QueryFiles(_m *Book) *BookFileQuery {
	query := (&BookFileClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(book.Table, book.FieldID, id),
			sqlgraph.To(bookfile.Table, bookfile.FieldID),
			sqlgraph.Edge(sqlgraph.M2M, true, book.FilesTable, book.FilesPrimaryKey...),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QueryReviews queries the reviews edge of a Book.
func (c *BookClient) QueryReviews(_m *Book) *BookReviewQuery {
	query := (&BookReviewClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(book.Table, book.FieldID, id),
			sqlgraph.To(bookreview.Table, bookreview.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, book.ReviewsTable, book.ReviewsColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QueryReadingProgress queries the reading_progress edge of a Book.
func (c *BookClient) QueryReadingProgress(_m *Book) *BookReadingProgressQuery {
	query := (&BookReadingProgressClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(book.Table, book.FieldID, id),
			sqlgraph.To(bookreadingprogress.Table, bookreadingprogress.FieldID),
			sqlgraph.Edge(sqlgraph.M2M, true, book.ReadingProgressTable, book.ReadingProgressPrimaryKey...),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QuerySearchIndex queries the search_index edge of a Book.
func (c *BookClient) QuerySearchIndex(_m *Book) *BookSearchIndexQuery {
	query := (&BookSearchIndexClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(book.Table, book.FieldID, id),
			sqlgraph.To(booksearchindex.Table, booksearchindex.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, book.SearchIndexTable, book.SearchIndexColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *BookClient) Hooks() []Hook {
	return c.hooks.Book
}

// Interceptors returns the client interceptors.
func (c *BookClient) Interceptors() []Interceptor {
	return c.inters.Book
}

func (c *BookClient) mutate(ctx context.Context, m *BookMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&BookCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&BookUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&BookUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&BookDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown Book mutation op: %q", m.Op())
	}
}

// BookDimensionClient is a client for the BookDimension schema.
type BookDimensionClient struct {
	config
}

// NewBookDimensionClient returns a client for the BookDimension from the given config.
func NewBookDimensionClient(c config) *BookDimensionClient {
	return &BookDimensionClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `bookdimension.Hooks(f(g(h())))`.
func (c *BookDimensionClient) Use(hooks ...Hook) {
	c.hooks.BookDimension = append(c.hooks.BookDimension, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `bookdimension.Intercept(f(g(h())))`.
func (c *BookDimensionClient) Intercept(interceptors ...Interceptor) {
	c.inters.BookDimension = append(c.inters.BookDimension, interceptors...)
}

// Create returns a builder for creating a BookDimension entity.
func (c *BookDimensionClient) Create() *BookDimensionCreate {
	mutation := newBookDimensionMutation(c.config, OpCreate)
	return &BookDimensionCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of BookDimension entities.
func (c *BookDimensionClient) CreateBulk(builders ...*BookDimensionCreate) *BookDimensionCreateBulk {
	return &BookDimensionCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *BookDimensionClient) MapCreateBulk(slice any, setFunc func(*BookDimensionCreate, int)) *BookDimensionCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &BookDimensionCreateBulk{err: fmt.Errorf("calling to BookDimensionClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*BookDimensionCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &BookDimensionCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for BookDimension.
func (c *BookDimensionClient) Update() *BookDimensionUpdate {
	mutation := newBookDimensionMutation(c.config, OpUpdate)
	return &BookDimensionUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *BookDimensionClient) UpdateOne(_m *BookDimension) *BookDimensionUpdateOne {
	mutation := newBookDimensionMutation(c.config, OpUpdateOne, withBookDimension(_m))
	return &BookDimensionUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *BookDimensionClient) UpdateOneID(id uuid.UUID) *BookDimensionUpdateOne {
	mutation := newBookDimensionMutation(c.config, OpUpdateOne, withBookDimensionID(id))
	return &BookDimensionUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for BookDimension.
func (c *BookDimensionClient) Delete() *BookDimensionDelete {
	mutation := newBookDimensionMutation(c.config, OpDelete)
	return &BookDimensionDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *BookDimensionClient) DeleteOne(_m *BookDimension) *BookDimensionDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *BookDimensionClient) DeleteOneID(id uuid.UUID) *BookDimensionDeleteOne {
	builder := c.Delete().Where(bookdimension.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &BookDimensionDeleteOne{builder}
}

// Query returns a query builder for BookDimension.
func (c *BookDimensionClient) Query() *BookDimensionQuery {
	return &BookDimensionQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeBookDimension},
		inters: c.Interceptors(),
	}
}

// Get returns a BookDimension entity by its id.
func (c *BookDimensionClient) Get(ctx context.Context, id uuid.UUID) (*BookDimension, error) {
	return c.Query().Where(bookdimension.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *BookDimensionClient) GetX(ctx context.Context, id uuid.UUID) *BookDimension {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryBook queries the book edge of a BookDimension.
func (c *BookDimensionClient) QueryBook(_m *BookDimension) *BookQuery {
	query := (&BookClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(bookdimension.Table, bookdimension.FieldID, id),
			sqlgraph.To(book.Table, book.FieldID),
			sqlgraph.Edge(sqlgraph.M2M, true, bookdimension.BookTable, bookdimension.BookPrimaryKey...),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QueryDimension queries the dimension edge of a BookDimension.
func (c *BookDimensionClient) QueryDimension(_m *BookDimension) *DimensionQuery {
	query := (&DimensionClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(bookdimension.Table, bookdimension.FieldID, id),
			sqlgraph.To(dimension.Table, dimension.FieldID),
			sqlgraph.Edge(sqlgraph.M2M, true, bookdimension.DimensionTable, bookdimension.DimensionPrimaryKey...),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *BookDimensionClient) Hooks() []Hook {
	return c.hooks.BookDimension
}

// Interceptors returns the client interceptors.
func (c *BookDimensionClient) Interceptors() []Interceptor {
	return c.inters.BookDimension
}

func (c *BookDimensionClient) mutate(ctx context.Context, m *BookDimensionMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&BookDimensionCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&BookDimensionUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&BookDimensionUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&BookDimensionDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown BookDimension mutation op: %q", m.Op())
	}
}

// BookFileClient is a client for the BookFile schema.
type BookFileClient struct {
	config
}

// NewBookFileClient returns a client for the BookFile from the given config.
func NewBookFileClient(c config) *BookFileClient {
	return &BookFileClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `bookfile.Hooks(f(g(h())))`.
func (c *BookFileClient) Use(hooks ...Hook) {
	c.hooks.BookFile = append(c.hooks.BookFile, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `bookfile.Intercept(f(g(h())))`.
func (c *BookFileClient) Intercept(interceptors ...Interceptor) {
	c.inters.BookFile = append(c.inters.BookFile, interceptors...)
}

// Create returns a builder for creating a BookFile entity.
func (c *BookFileClient) Create() *BookFileCreate {
	mutation := newBookFileMutation(c.config, OpCreate)
	return &BookFileCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of BookFile entities.
func (c *BookFileClient) CreateBulk(builders ...*BookFileCreate) *BookFileCreateBulk {
	return &BookFileCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *BookFileClient) MapCreateBulk(slice any, setFunc func(*BookFileCreate, int)) *BookFileCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &BookFileCreateBulk{err: fmt.Errorf("calling to BookFileClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*BookFileCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &BookFileCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for BookFile.
func (c *BookFileClient) Update() *BookFileUpdate {
	mutation := newBookFileMutation(c.config, OpUpdate)
	return &BookFileUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *BookFileClient) UpdateOne(_m *BookFile) *BookFileUpdateOne {
	mutation := newBookFileMutation(c.config, OpUpdateOne, withBookFile(_m))
	return &BookFileUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *BookFileClient) UpdateOneID(id uuid.UUID) *BookFileUpdateOne {
	mutation := newBookFileMutation(c.config, OpUpdateOne, withBookFileID(id))
	return &BookFileUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for BookFile.
func (c *BookFileClient) Delete() *BookFileDelete {
	mutation := newBookFileMutation(c.config, OpDelete)
	return &BookFileDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *BookFileClient) DeleteOne(_m *BookFile) *BookFileDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *BookFileClient) DeleteOneID(id uuid.UUID) *BookFileDeleteOne {
	builder := c.Delete().Where(bookfile.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &BookFileDeleteOne{builder}
}

// Query returns a query builder for BookFile.
func (c *BookFileClient) Query() *BookFileQuery {
	return &BookFileQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeBookFile},
		inters: c.Interceptors(),
	}
}

// Get returns a BookFile entity by its id.
func (c *BookFileClient) Get(ctx context.Context, id uuid.UUID) (*BookFile, error) {
	return c.Query().Where(bookfile.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *BookFileClient) GetX(ctx context.Context, id uuid.UUID) *BookFile {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryBook queries the book edge of a BookFile.
func (c *BookFileClient) QueryBook(_m *BookFile) *BookQuery {
	query := (&BookClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(bookfile.Table, bookfile.FieldID, id),
			sqlgraph.To(book.Table, book.FieldID),
			sqlgraph.Edge(sqlgraph.M2M, false, bookfile.BookTable, bookfile.BookPrimaryKey...),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QueryUploader queries the uploader edge of a BookFile.
func (c *BookFileClient) QueryUploader(_m *BookFile) *UserQuery {
	query := (&UserClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(bookfile.Table, bookfile.FieldID, id),
			sqlgraph.To(user.Table, user.FieldID),
			sqlgraph.Edge(sqlgraph.M2M, false, bookfile.UploaderTable, bookfile.UploaderPrimaryKey...),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *BookFileClient) Hooks() []Hook {
	return c.hooks.BookFile
}

// Interceptors returns the client interceptors.
func (c *BookFileClient) Interceptors() []Interceptor {
	return c.inters.BookFile
}

func (c *BookFileClient) mutate(ctx context.Context, m *BookFileMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&BookFileCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&BookFileUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&BookFileUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&BookFileDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown BookFile mutation op: %q", m.Op())
	}
}

// BookReadingProgressClient is a client for the BookReadingProgress schema.
type BookReadingProgressClient struct {
	config
}

// NewBookReadingProgressClient returns a client for the BookReadingProgress from the given config.
func NewBookReadingProgressClient(c config) *BookReadingProgressClient {
	return &BookReadingProgressClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `bookreadingprogress.Hooks(f(g(h())))`.
func (c *BookReadingProgressClient) Use(hooks ...Hook) {
	c.hooks.BookReadingProgress = append(c.hooks.BookReadingProgress, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `bookreadingprogress.Intercept(f(g(h())))`.
func (c *BookReadingProgressClient) Intercept(interceptors ...Interceptor) {
	c.inters.BookReadingProgress = append(c.inters.BookReadingProgress, interceptors...)
}

// Create returns a builder for creating a BookReadingProgress entity.
func (c *BookReadingProgressClient) Create() *BookReadingProgressCreate {
	mutation := newBookReadingProgressMutation(c.config, OpCreate)
	return &BookReadingProgressCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of BookReadingProgress entities.
func (c *BookReadingProgressClient) CreateBulk(builders ...*BookReadingProgressCreate) *BookReadingProgressCreateBulk {
	return &BookReadingProgressCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *BookReadingProgressClient) MapCreateBulk(slice any, setFunc func(*BookReadingProgressCreate, int)) *BookReadingProgressCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &BookReadingProgressCreateBulk{err: fmt.Errorf("calling to BookReadingProgressClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*BookReadingProgressCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &BookReadingProgressCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for BookReadingProgress.
func (c *BookReadingProgressClient) Update() *BookReadingProgressUpdate {
	mutation := newBookReadingProgressMutation(c.config, OpUpdate)
	return &BookReadingProgressUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *BookReadingProgressClient) UpdateOne(_m *BookReadingProgress) *BookReadingProgressUpdateOne {
	mutation := newBookReadingProgressMutation(c.config, OpUpdateOne, withBookReadingProgress(_m))
	return &BookReadingProgressUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *BookReadingProgressClient) UpdateOneID(id uuid.UUID) *BookReadingProgressUpdateOne {
	mutation := newBookReadingProgressMutation(c.config, OpUpdateOne, withBookReadingProgressID(id))
	return &BookReadingProgressUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for BookReadingProgress.
func (c *BookReadingProgressClient) Delete() *BookReadingProgressDelete {
	mutation := newBookReadingProgressMutation(c.config, OpDelete)
	return &BookReadingProgressDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *BookReadingProgressClient) DeleteOne(_m *BookReadingProgress) *BookReadingProgressDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *BookReadingProgressClient) DeleteOneID(id uuid.UUID) *BookReadingProgressDeleteOne {
	builder := c.Delete().Where(bookreadingprogress.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &BookReadingProgressDeleteOne{builder}
}

// Query returns a query builder for BookReadingProgress.
func (c *BookReadingProgressClient) Query() *BookReadingProgressQuery {
	return &BookReadingProgressQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeBookReadingProgress},
		inters: c.Interceptors(),
	}
}

// Get returns a BookReadingProgress entity by its id.
func (c *BookReadingProgressClient) Get(ctx context.Context, id uuid.UUID) (*BookReadingProgress, error) {
	return c.Query().Where(bookreadingprogress.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *BookReadingProgressClient) GetX(ctx context.Context, id uuid.UUID) *BookReadingProgress {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryBook queries the book edge of a BookReadingProgress.
func (c *BookReadingProgressClient) QueryBook(_m *BookReadingProgress) *BookQuery {
	query := (&BookClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(bookreadingprogress.Table, bookreadingprogress.FieldID, id),
			sqlgraph.To(book.Table, book.FieldID),
			sqlgraph.Edge(sqlgraph.M2M, false, bookreadingprogress.BookTable, bookreadingprogress.BookPrimaryKey...),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QueryUser queries the user edge of a BookReadingProgress.
func (c *BookReadingProgressClient) QueryUser(_m *BookReadingProgress) *UserQuery {
	query := (&UserClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(bookreadingprogress.Table, bookreadingprogress.FieldID, id),
			sqlgraph.To(user.Table, user.FieldID),
			sqlgraph.Edge(sqlgraph.M2M, false, bookreadingprogress.UserTable, bookreadingprogress.UserPrimaryKey...),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *BookReadingProgressClient) Hooks() []Hook {
	return c.hooks.BookReadingProgress
}

// Interceptors returns the client interceptors.
func (c *BookReadingProgressClient) Interceptors() []Interceptor {
	return c.inters.BookReadingProgress
}

func (c *BookReadingProgressClient) mutate(ctx context.Context, m *BookReadingProgressMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&BookReadingProgressCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&BookReadingProgressUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&BookReadingProgressUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&BookReadingProgressDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown BookReadingProgress mutation op: %q", m.Op())
	}
}

// BookReviewClient is a client for the BookReview schema.
type BookReviewClient struct {
	config
}

// NewBookReviewClient returns a client for the BookReview from the given config.
func NewBookReviewClient(c config) *BookReviewClient {
	return &BookReviewClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `bookreview.Hooks(f(g(h())))`.
func (c *BookReviewClient) Use(hooks ...Hook) {
	c.hooks.BookReview = append(c.hooks.BookReview, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `bookreview.Intercept(f(g(h())))`.
func (c *BookReviewClient) Intercept(interceptors ...Interceptor) {
	c.inters.BookReview = append(c.inters.BookReview, interceptors...)
}

// Create returns a builder for creating a BookReview entity.
func (c *BookReviewClient) Create() *BookReviewCreate {
	mutation := newBookReviewMutation(c.config, OpCreate)
	return &BookReviewCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of BookReview entities.
func (c *BookReviewClient) CreateBulk(builders ...*BookReviewCreate) *BookReviewCreateBulk {
	return &BookReviewCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *BookReviewClient) MapCreateBulk(slice any, setFunc func(*BookReviewCreate, int)) *BookReviewCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &BookReviewCreateBulk{err: fmt.Errorf("calling to BookReviewClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*BookReviewCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &BookReviewCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for BookReview.
func (c *BookReviewClient) Update() *BookReviewUpdate {
	mutation := newBookReviewMutation(c.config, OpUpdate)
	return &BookReviewUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *BookReviewClient) UpdateOne(_m *BookReview) *BookReviewUpdateOne {
	mutation := newBookReviewMutation(c.config, OpUpdateOne, withBookReview(_m))
	return &BookReviewUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *BookReviewClient) UpdateOneID(id uuid.UUID) *BookReviewUpdateOne {
	mutation := newBookReviewMutation(c.config, OpUpdateOne, withBookReviewID(id))
	return &BookReviewUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for BookReview.
func (c *BookReviewClient) Delete() *BookReviewDelete {
	mutation := newBookReviewMutation(c.config, OpDelete)
	return &BookReviewDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *BookReviewClient) DeleteOne(_m *BookReview) *BookReviewDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *BookReviewClient) DeleteOneID(id uuid.UUID) *BookReviewDeleteOne {
	builder := c.Delete().Where(bookreview.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &BookReviewDeleteOne{builder}
}

// Query returns a query builder for BookReview.
func (c *BookReviewClient) Query() *BookReviewQuery {
	return &BookReviewQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeBookReview},
		inters: c.Interceptors(),
	}
}

// Get returns a BookReview entity by its id.
func (c *BookReviewClient) Get(ctx context.Context, id uuid.UUID) (*BookReview, error) {
	return c.Query().Where(bookreview.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *BookReviewClient) GetX(ctx context.Context, id uuid.UUID) *BookReview {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryBook queries the book edge of a BookReview.
func (c *BookReviewClient) QueryBook(_m *BookReview) *BookQuery {
	query := (&BookClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(bookreview.Table, bookreview.FieldID, id),
			sqlgraph.To(book.Table, book.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, bookreview.BookTable, bookreview.BookColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QueryReviewer queries the reviewer edge of a BookReview.
func (c *BookReviewClient) QueryReviewer(_m *BookReview) *UserQuery {
	query := (&UserClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(bookreview.Table, bookreview.FieldID, id),
			sqlgraph.To(user.Table, user.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, bookreview.ReviewerTable, bookreview.ReviewerColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *BookReviewClient) Hooks() []Hook {
	return c.hooks.BookReview
}

// Interceptors returns the client interceptors.
func (c *BookReviewClient) Interceptors() []Interceptor {
	return c.inters.BookReview
}

func (c *BookReviewClient) mutate(ctx context.Context, m *BookReviewMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&BookReviewCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&BookReviewUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&BookReviewUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&BookReviewDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown BookReview mutation op: %q", m.Op())
	}
}

// BookSearchIndexClient is a client for the BookSearchIndex schema.
type BookSearchIndexClient struct {
	config
}

// NewBookSearchIndexClient returns a client for the BookSearchIndex from the given config.
func NewBookSearchIndexClient(c config) *BookSearchIndexClient {
	return &BookSearchIndexClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `booksearchindex.Hooks(f(g(h())))`.
func (c *BookSearchIndexClient) Use(hooks ...Hook) {
	c.hooks.BookSearchIndex = append(c.hooks.BookSearchIndex, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `booksearchindex.Intercept(f(g(h())))`.
func (c *BookSearchIndexClient) Intercept(interceptors ...Interceptor) {
	c.inters.BookSearchIndex = append(c.inters.BookSearchIndex, interceptors...)
}

// Create returns a builder for creating a BookSearchIndex entity.
func (c *BookSearchIndexClient) Create() *BookSearchIndexCreate {
	mutation := newBookSearchIndexMutation(c.config, OpCreate)
	return &BookSearchIndexCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of BookSearchIndex entities.
func (c *BookSearchIndexClient) CreateBulk(builders ...*BookSearchIndexCreate) *BookSearchIndexCreateBulk {
	return &BookSearchIndexCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *BookSearchIndexClient) MapCreateBulk(slice any, setFunc func(*BookSearchIndexCreate, int)) *BookSearchIndexCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &BookSearchIndexCreateBulk{err: fmt.Errorf("calling to BookSearchIndexClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*BookSearchIndexCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &BookSearchIndexCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for BookSearchIndex.
func (c *BookSearchIndexClient) Update() *BookSearchIndexUpdate {
	mutation := newBookSearchIndexMutation(c.config, OpUpdate)
	return &BookSearchIndexUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *BookSearchIndexClient) UpdateOne(_m *BookSearchIndex) *BookSearchIndexUpdateOne {
	mutation := newBookSearchIndexMutation(c.config, OpUpdateOne, withBookSearchIndex(_m))
	return &BookSearchIndexUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *BookSearchIndexClient) UpdateOneID(id uuid.UUID) *BookSearchIndexUpdateOne {
	mutation := newBookSearchIndexMutation(c.config, OpUpdateOne, withBookSearchIndexID(id))
	return &BookSearchIndexUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for BookSearchIndex.
func (c *BookSearchIndexClient) Delete() *BookSearchIndexDelete {
	mutation := newBookSearchIndexMutation(c.config, OpDelete)
	return &BookSearchIndexDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *BookSearchIndexClient) DeleteOne(_m *BookSearchIndex) *BookSearchIndexDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *BookSearchIndexClient) DeleteOneID(id uuid.UUID) *BookSearchIndexDeleteOne {
	builder := c.Delete().Where(booksearchindex.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &BookSearchIndexDeleteOne{builder}
}

// Query returns a query builder for BookSearchIndex.
func (c *BookSearchIndexClient) Query() *BookSearchIndexQuery {
	return &BookSearchIndexQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeBookSearchIndex},
		inters: c.Interceptors(),
	}
}

// Get returns a BookSearchIndex entity by its id.
func (c *BookSearchIndexClient) Get(ctx context.Context, id uuid.UUID) (*BookSearchIndex, error) {
	return c.Query().Where(booksearchindex.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *BookSearchIndexClient) GetX(ctx context.Context, id uuid.UUID) *BookSearchIndex {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryBook queries the book edge of a BookSearchIndex.
func (c *BookSearchIndexClient) QueryBook(_m *BookSearchIndex) *BookQuery {
	query := (&BookClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(booksearchindex.Table, booksearchindex.FieldID, id),
			sqlgraph.To(book.Table, book.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, booksearchindex.BookTable, booksearchindex.BookColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *BookSearchIndexClient) Hooks() []Hook {
	return c.hooks.BookSearchIndex
}

// Interceptors returns the client interceptors.
func (c *BookSearchIndexClient) Interceptors() []Interceptor {
	return c.inters.BookSearchIndex
}

func (c *BookSearchIndexClient) mutate(ctx context.Context, m *BookSearchIndexMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&BookSearchIndexCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&BookSearchIndexUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&BookSearchIndexUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&BookSearchIndexDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown BookSearchIndex mutation op: %q", m.Op())
	}
}

// DimensionClient is a client for the Dimension schema.
type DimensionClient struct {
	config
}

// NewDimensionClient returns a client for the Dimension from the given config.
func NewDimensionClient(c config) *DimensionClient {
	return &DimensionClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `dimension.Hooks(f(g(h())))`.
func (c *DimensionClient) Use(hooks ...Hook) {
	c.hooks.Dimension = append(c.hooks.Dimension, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `dimension.Intercept(f(g(h())))`.
func (c *DimensionClient) Intercept(interceptors ...Interceptor) {
	c.inters.Dimension = append(c.inters.Dimension, interceptors...)
}

// Create returns a builder for creating a Dimension entity.
func (c *DimensionClient) Create() *DimensionCreate {
	mutation := newDimensionMutation(c.config, OpCreate)
	return &DimensionCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of Dimension entities.
func (c *DimensionClient) CreateBulk(builders ...*DimensionCreate) *DimensionCreateBulk {
	return &DimensionCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *DimensionClient) MapCreateBulk(slice any, setFunc func(*DimensionCreate, int)) *DimensionCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &DimensionCreateBulk{err: fmt.Errorf("calling to DimensionClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*DimensionCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &DimensionCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for Dimension.
func (c *DimensionClient) Update() *DimensionUpdate {
	mutation := newDimensionMutation(c.config, OpUpdate)
	return &DimensionUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *DimensionClient) UpdateOne(_m *Dimension) *DimensionUpdateOne {
	mutation := newDimensionMutation(c.config, OpUpdateOne, withDimension(_m))
	return &DimensionUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *DimensionClient) UpdateOneID(id uuid.UUID) *DimensionUpdateOne {
	mutation := newDimensionMutation(c.config, OpUpdateOne, withDimensionID(id))
	return &DimensionUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for Dimension.
func (c *DimensionClient) Delete() *DimensionDelete {
	mutation := newDimensionMutation(c.config, OpDelete)
	return &DimensionDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *DimensionClient) DeleteOne(_m *Dimension) *DimensionDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *DimensionClient) DeleteOneID(id uuid.UUID) *DimensionDeleteOne {
	builder := c.Delete().Where(dimension.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &DimensionDeleteOne{builder}
}

// Query returns a query builder for Dimension.
func (c *DimensionClient) Query() *DimensionQuery {
	return &DimensionQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeDimension},
		inters: c.Interceptors(),
	}
}

// Get returns a Dimension entity by its id.
func (c *DimensionClient) Get(ctx context.Context, id uuid.UUID) (*Dimension, error) {
	return c.Query().Where(dimension.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *DimensionClient) GetX(ctx context.Context, id uuid.UUID) *Dimension {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryParent queries the parent edge of a Dimension.
func (c *DimensionClient) QueryParent(_m *Dimension) *DimensionQuery {
	query := (&DimensionClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(dimension.Table, dimension.FieldID, id),
			sqlgraph.To(dimension.Table, dimension.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, dimension.ParentTable, dimension.ParentColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QueryChildren queries the children edge of a Dimension.
func (c *DimensionClient) QueryChildren(_m *Dimension) *DimensionQuery {
	query := (&DimensionClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(dimension.Table, dimension.FieldID, id),
			sqlgraph.To(dimension.Table, dimension.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, dimension.ChildrenTable, dimension.ChildrenColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QueryBookDimensions queries the book_dimensions edge of a Dimension.
func (c *DimensionClient) QueryBookDimensions(_m *Dimension) *BookDimensionQuery {
	query := (&BookDimensionClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(dimension.Table, dimension.FieldID, id),
			sqlgraph.To(bookdimension.Table, bookdimension.FieldID),
			sqlgraph.Edge(sqlgraph.M2M, false, dimension.BookDimensionsTable, dimension.BookDimensionsPrimaryKey...),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *DimensionClient) Hooks() []Hook {
	return c.hooks.Dimension
}

// Interceptors returns the client interceptors.
func (c *DimensionClient) Interceptors() []Interceptor {
	return c.inters.Dimension
}

func (c *DimensionClient) mutate(ctx context.Context, m *DimensionMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&DimensionCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&DimensionUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&DimensionUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&DimensionDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown Dimension mutation op: %q", m.Op())
	}
}

// UserClient is a client for the User schema.
type UserClient struct {
	config
}

// NewUserClient returns a client for the User from the given config.
func NewUserClient(c config) *UserClient {
	return &UserClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `user.Hooks(f(g(h())))`.
func (c *UserClient) Use(hooks ...Hook) {
	c.hooks.User = append(c.hooks.User, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `user.Intercept(f(g(h())))`.
func (c *UserClient) Intercept(interceptors ...Interceptor) {
	c.inters.User = append(c.inters.User, interceptors...)
}

// Create returns a builder for creating a User entity.
func (c *UserClient) Create() *UserCreate {
	mutation := newUserMutation(c.config, OpCreate)
	return &UserCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of User entities.
func (c *UserClient) CreateBulk(builders ...*UserCreate) *UserCreateBulk {
	return &UserCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *UserClient) MapCreateBulk(slice any, setFunc func(*UserCreate, int)) *UserCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &UserCreateBulk{err: fmt.Errorf("calling to UserClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*UserCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &UserCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for User.
func (c *UserClient) Update() *UserUpdate {
	mutation := newUserMutation(c.config, OpUpdate)
	return &UserUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *UserClient) UpdateOne(_m *User) *UserUpdateOne {
	mutation := newUserMutation(c.config, OpUpdateOne, withUser(_m))
	return &UserUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *UserClient) UpdateOneID(id uuid.UUID) *UserUpdateOne {
	mutation := newUserMutation(c.config, OpUpdateOne, withUserID(id))
	return &UserUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for User.
func (c *UserClient) Delete() *UserDelete {
	mutation := newUserMutation(c.config, OpDelete)
	return &UserDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *UserClient) DeleteOne(_m *User) *UserDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *UserClient) DeleteOneID(id uuid.UUID) *UserDeleteOne {
	builder := c.Delete().Where(user.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &UserDeleteOne{builder}
}

// Query returns a query builder for User.
func (c *UserClient) Query() *UserQuery {
	return &UserQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeUser},
		inters: c.Interceptors(),
	}
}

// Get returns a User entity by its id.
func (c *UserClient) Get(ctx context.Context, id uuid.UUID) (*User, error) {
	return c.Query().Where(user.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *UserClient) GetX(ctx context.Context, id uuid.UUID) *User {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryBooks queries the books edge of a User.
func (c *UserClient) QueryBooks(_m *User) *BookQuery {
	query := (&BookClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(user.Table, user.FieldID, id),
			sqlgraph.To(book.Table, book.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, user.BooksTable, user.BooksColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QueryUploadedFiles queries the uploaded_files edge of a User.
func (c *UserClient) QueryUploadedFiles(_m *User) *BookFileQuery {
	query := (&BookFileClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(user.Table, user.FieldID, id),
			sqlgraph.To(bookfile.Table, bookfile.FieldID),
			sqlgraph.Edge(sqlgraph.M2M, true, user.UploadedFilesTable, user.UploadedFilesPrimaryKey...),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QueryReadingProgress queries the reading_progress edge of a User.
func (c *UserClient) QueryReadingProgress(_m *User) *BookReadingProgressQuery {
	query := (&BookReadingProgressClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(user.Table, user.FieldID, id),
			sqlgraph.To(bookreadingprogress.Table, bookreadingprogress.FieldID),
			sqlgraph.Edge(sqlgraph.M2M, true, user.ReadingProgressTable, user.ReadingProgressPrimaryKey...),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QueryReviews queries the reviews edge of a User.
func (c *UserClient) QueryReviews(_m *User) *BookReviewQuery {
	query := (&BookReviewClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(user.Table, user.FieldID, id),
			sqlgraph.To(bookreview.Table, bookreview.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, user.ReviewsTable, user.ReviewsColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *UserClient) Hooks() []Hook {
	return c.hooks.User
}

// Interceptors returns the client interceptors.
func (c *UserClient) Interceptors() []Interceptor {
	return c.inters.User
}

func (c *UserClient) mutate(ctx context.Context, m *UserMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&UserCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&UserUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&UserUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&UserDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown User mutation op: %q", m.Op())
	}
}

// hooks and interceptors per client, for fast access.
type (
	hooks struct {
		Book, BookDimension, BookFile, BookReadingProgress, BookReview, BookSearchIndex,
		Dimension, User []ent.Hook
	}
	inters struct {
		Book, BookDimension, BookFile, BookReadingProgress, BookReview, BookSearchIndex,
		Dimension, User []ent.Interceptor
	}
)
