// Code generated by ent, DO NOT EDIT.

package ent

import (
	"time"

	"github.com/google/uuid"
	"github.com/zhoumingjun/bookmgr/backend/ent/book"
	"github.com/zhoumingjun/bookmgr/backend/ent/bookdimension"
	"github.com/zhoumingjun/bookmgr/backend/ent/bookfile"
	"github.com/zhoumingjun/bookmgr/backend/ent/bookreadingprogress"
	"github.com/zhoumingjun/bookmgr/backend/ent/bookreview"
	"github.com/zhoumingjun/bookmgr/backend/ent/booksearchindex"
	"github.com/zhoumingjun/bookmgr/backend/ent/dimension"
	"github.com/zhoumingjun/bookmgr/backend/ent/schema"
	"github.com/zhoumingjun/bookmgr/backend/ent/user"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	bookFields := schema.Book{}.Fields()
	_ = bookFields
	// bookDescTitle is the schema descriptor for title field.
	bookDescTitle := bookFields[1].Descriptor()
	// book.TitleValidator is a validator for the "title" field. It is called by the builders before save.
	book.TitleValidator = func() func(string) error {
		validators := bookDescTitle.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(title string) error {
			for _, fn := range fns {
				if err := fn(title); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// bookDescAuthor is the schema descriptor for author field.
	bookDescAuthor := bookFields[2].Descriptor()
	// book.AuthorValidator is a validator for the "author" field. It is called by the builders before save.
	book.AuthorValidator = bookDescAuthor.Validators[0].(func(string) error)
	// bookDescDescription is the schema descriptor for description field.
	bookDescDescription := bookFields[3].Descriptor()
	// book.DefaultDescription holds the default value on creation for the description field.
	book.DefaultDescription = bookDescDescription.Default.(string)
	// bookDescCoreGoal is the schema descriptor for core_goal field.
	bookDescCoreGoal := bookFields[6].Descriptor()
	// book.DefaultCoreGoal holds the default value on creation for the core_goal field.
	book.DefaultCoreGoal = bookDescCoreGoal.Default.(string)
	// bookDescCognitiveLevel is the schema descriptor for cognitive_level field.
	bookDescCognitiveLevel := bookFields[7].Descriptor()
	// book.DefaultCognitiveLevel holds the default value on creation for the cognitive_level field.
	book.DefaultCognitiveLevel = bookDescCognitiveLevel.Default.(string)
	// book.CognitiveLevelValidator is a validator for the "cognitive_level" field. It is called by the builders before save.
	book.CognitiveLevelValidator = bookDescCognitiveLevel.Validators[0].(func(string) error)
	// bookDescResourceType is the schema descriptor for resource_type field.
	bookDescResourceType := bookFields[8].Descriptor()
	// book.DefaultResourceType holds the default value on creation for the resource_type field.
	book.DefaultResourceType = bookDescResourceType.Default.(string)
	// book.ResourceTypeValidator is a validator for the "resource_type" field. It is called by the builders before save.
	book.ResourceTypeValidator = bookDescResourceType.Validators[0].(func(string) error)
	// bookDescHasPrint is the schema descriptor for has_print field.
	bookDescHasPrint := bookFields[9].Descriptor()
	// book.DefaultHasPrint holds the default value on creation for the has_print field.
	book.DefaultHasPrint = bookDescHasPrint.Default.(bool)
	// bookDescHasDigital is the schema descriptor for has_digital field.
	bookDescHasDigital := bookFields[10].Descriptor()
	// book.DefaultHasDigital holds the default value on creation for the has_digital field.
	book.DefaultHasDigital = bookDescHasDigital.Default.(bool)
	// bookDescHasAudio is the schema descriptor for has_audio field.
	bookDescHasAudio := bookFields[11].Descriptor()
	// book.DefaultHasAudio holds the default value on creation for the has_audio field.
	book.DefaultHasAudio = bookDescHasAudio.Default.(bool)
	// bookDescHasVideo is the schema descriptor for has_video field.
	bookDescHasVideo := bookFields[12].Descriptor()
	// book.DefaultHasVideo holds the default value on creation for the has_video field.
	book.DefaultHasVideo = bookDescHasVideo.Default.(bool)
	// bookDescTeachingSuggestion is the schema descriptor for teaching_suggestion field.
	bookDescTeachingSuggestion := bookFields[13].Descriptor()
	// book.DefaultTeachingSuggestion holds the default value on creation for the teaching_suggestion field.
	book.DefaultTeachingSuggestion = bookDescTeachingSuggestion.Default.(string)
	// bookDescParentReadingGuide is the schema descriptor for parent_reading_guide field.
	bookDescParentReadingGuide := bookFields[14].Descriptor()
	// book.DefaultParentReadingGuide holds the default value on creation for the parent_reading_guide field.
	book.DefaultParentReadingGuide = bookDescParentReadingGuide.Default.(string)
	// bookDescRecommendedAgeMin is the schema descriptor for recommended_age_min field.
	bookDescRecommendedAgeMin := bookFields[15].Descriptor()
	// book.DefaultRecommendedAgeMin holds the default value on creation for the recommended_age_min field.
	book.DefaultRecommendedAgeMin = bookDescRecommendedAgeMin.Default.(int)
	// bookDescRecommendedAgeMax is the schema descriptor for recommended_age_max field.
	bookDescRecommendedAgeMax := bookFields[16].Descriptor()
	// book.DefaultRecommendedAgeMax holds the default value on creation for the recommended_age_max field.
	book.DefaultRecommendedAgeMax = bookDescRecommendedAgeMax.Default.(int)
	// bookDescCoverImageURL is the schema descriptor for cover_image_url field.
	bookDescCoverImageURL := bookFields[17].Descriptor()
	// book.DefaultCoverImageURL holds the default value on creation for the cover_image_url field.
	book.DefaultCoverImageURL = bookDescCoverImageURL.Default.(string)
	// book.CoverImageURLValidator is a validator for the "cover_image_url" field. It is called by the builders before save.
	book.CoverImageURLValidator = bookDescCoverImageURL.Validators[0].(func(string) error)
	// bookDescCoverURL is the schema descriptor for cover_url field.
	bookDescCoverURL := bookFields[18].Descriptor()
	// book.DefaultCoverURL holds the default value on creation for the cover_url field.
	book.DefaultCoverURL = bookDescCoverURL.Default.(string)
	// book.CoverURLValidator is a validator for the "cover_url" field. It is called by the builders before save.
	book.CoverURLValidator = bookDescCoverURL.Validators[0].(func(string) error)
	// bookDescFilePath is the schema descriptor for file_path field.
	bookDescFilePath := bookFields[19].Descriptor()
	// book.DefaultFilePath holds the default value on creation for the file_path field.
	book.DefaultFilePath = bookDescFilePath.Default.(string)
	// bookDescStatus is the schema descriptor for status field.
	bookDescStatus := bookFields[20].Descriptor()
	// book.DefaultStatus holds the default value on creation for the status field.
	book.DefaultStatus = bookDescStatus.Default.(string)
	// book.StatusValidator is a validator for the "status" field. It is called by the builders before save.
	book.StatusValidator = bookDescStatus.Validators[0].(func(string) error)
	// bookDescViewCount is the schema descriptor for view_count field.
	bookDescViewCount := bookFields[22].Descriptor()
	// book.DefaultViewCount holds the default value on creation for the view_count field.
	book.DefaultViewCount = bookDescViewCount.Default.(int)
	// bookDescCreatedAt is the schema descriptor for created_at field.
	bookDescCreatedAt := bookFields[23].Descriptor()
	// book.DefaultCreatedAt holds the default value on creation for the created_at field.
	book.DefaultCreatedAt = bookDescCreatedAt.Default.(func() time.Time)
	// bookDescUpdatedAt is the schema descriptor for updated_at field.
	bookDescUpdatedAt := bookFields[24].Descriptor()
	// book.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	book.DefaultUpdatedAt = bookDescUpdatedAt.Default.(func() time.Time)
	// book.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	book.UpdateDefaultUpdatedAt = bookDescUpdatedAt.UpdateDefault.(func() time.Time)
	// bookDescID is the schema descriptor for id field.
	bookDescID := bookFields[0].Descriptor()
	// book.DefaultID holds the default value on creation for the id field.
	book.DefaultID = bookDescID.Default.(func() uuid.UUID)
	bookdimensionFields := schema.BookDimension{}.Fields()
	_ = bookdimensionFields
	// bookdimensionDescIsPrimary is the schema descriptor for is_primary field.
	bookdimensionDescIsPrimary := bookdimensionFields[1].Descriptor()
	// bookdimension.DefaultIsPrimary holds the default value on creation for the is_primary field.
	bookdimension.DefaultIsPrimary = bookdimensionDescIsPrimary.Default.(bool)
	// bookdimensionDescCreatedAt is the schema descriptor for created_at field.
	bookdimensionDescCreatedAt := bookdimensionFields[2].Descriptor()
	// bookdimension.DefaultCreatedAt holds the default value on creation for the created_at field.
	bookdimension.DefaultCreatedAt = bookdimensionDescCreatedAt.Default.(func() time.Time)
	// bookdimensionDescID is the schema descriptor for id field.
	bookdimensionDescID := bookdimensionFields[0].Descriptor()
	// bookdimension.DefaultID holds the default value on creation for the id field.
	bookdimension.DefaultID = bookdimensionDescID.Default.(func() uuid.UUID)
	bookfileFields := schema.BookFile{}.Fields()
	_ = bookfileFields
	// bookfileDescFileType is the schema descriptor for file_type field.
	bookfileDescFileType := bookfileFields[2].Descriptor()
	// bookfile.FileTypeValidator is a validator for the "file_type" field. It is called by the builders before save.
	bookfile.FileTypeValidator = func() func(string) error {
		validators := bookfileDescFileType.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(file_type string) error {
			for _, fn := range fns {
				if err := fn(file_type); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// bookfileDescOriginalName is the schema descriptor for original_name field.
	bookfileDescOriginalName := bookfileFields[3].Descriptor()
	// bookfile.OriginalNameValidator is a validator for the "original_name" field. It is called by the builders before save.
	bookfile.OriginalNameValidator = func() func(string) error {
		validators := bookfileDescOriginalName.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(original_name string) error {
			for _, fn := range fns {
				if err := fn(original_name); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// bookfileDescStoredName is the schema descriptor for stored_name field.
	bookfileDescStoredName := bookfileFields[4].Descriptor()
	// bookfile.StoredNameValidator is a validator for the "stored_name" field. It is called by the builders before save.
	bookfile.StoredNameValidator = func() func(string) error {
		validators := bookfileDescStoredName.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(stored_name string) error {
			for _, fn := range fns {
				if err := fn(stored_name); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// bookfileDescFilePath is the schema descriptor for file_path field.
	bookfileDescFilePath := bookfileFields[5].Descriptor()
	// bookfile.FilePathValidator is a validator for the "file_path" field. It is called by the builders before save.
	bookfile.FilePathValidator = func() func(string) error {
		validators := bookfileDescFilePath.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(file_path string) error {
			for _, fn := range fns {
				if err := fn(file_path); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// bookfileDescMimeType is the schema descriptor for mime_type field.
	bookfileDescMimeType := bookfileFields[7].Descriptor()
	// bookfile.DefaultMimeType holds the default value on creation for the mime_type field.
	bookfile.DefaultMimeType = bookfileDescMimeType.Default.(string)
	// bookfile.MimeTypeValidator is a validator for the "mime_type" field. It is called by the builders before save.
	bookfile.MimeTypeValidator = bookfileDescMimeType.Validators[0].(func(string) error)
	// bookfileDescCreatedAt is the schema descriptor for created_at field.
	bookfileDescCreatedAt := bookfileFields[9].Descriptor()
	// bookfile.DefaultCreatedAt holds the default value on creation for the created_at field.
	bookfile.DefaultCreatedAt = bookfileDescCreatedAt.Default.(func() time.Time)
	// bookfileDescID is the schema descriptor for id field.
	bookfileDescID := bookfileFields[0].Descriptor()
	// bookfile.DefaultID holds the default value on creation for the id field.
	bookfile.DefaultID = bookfileDescID.Default.(func() uuid.UUID)
	bookreadingprogressFields := schema.BookReadingProgress{}.Fields()
	_ = bookreadingprogressFields
	// bookreadingprogressDescProgressPercent is the schema descriptor for progress_percent field.
	bookreadingprogressDescProgressPercent := bookreadingprogressFields[3].Descriptor()
	// bookreadingprogress.DefaultProgressPercent holds the default value on creation for the progress_percent field.
	bookreadingprogress.DefaultProgressPercent = bookreadingprogressDescProgressPercent.Default.(int)
	// bookreadingprogress.ProgressPercentValidator is a validator for the "progress_percent" field. It is called by the builders before save.
	bookreadingprogress.ProgressPercentValidator = func() func(int) error {
		validators := bookreadingprogressDescProgressPercent.Validators
		fns := [...]func(int) error{
			validators[0].(func(int) error),
			validators[1].(func(int) error),
		}
		return func(progress_percent int) error {
			for _, fn := range fns {
				if err := fn(progress_percent); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// bookreadingprogressDescLastPage is the schema descriptor for last_page field.
	bookreadingprogressDescLastPage := bookreadingprogressFields[4].Descriptor()
	// bookreadingprogress.DefaultLastPage holds the default value on creation for the last_page field.
	bookreadingprogress.DefaultLastPage = bookreadingprogressDescLastPage.Default.(int)
	// bookreadingprogress.LastPageValidator is a validator for the "last_page" field. It is called by the builders before save.
	bookreadingprogress.LastPageValidator = bookreadingprogressDescLastPage.Validators[0].(func(int) error)
	// bookreadingprogressDescLastReadAt is the schema descriptor for last_read_at field.
	bookreadingprogressDescLastReadAt := bookreadingprogressFields[5].Descriptor()
	// bookreadingprogress.DefaultLastReadAt holds the default value on creation for the last_read_at field.
	bookreadingprogress.DefaultLastReadAt = bookreadingprogressDescLastReadAt.Default.(func() time.Time)
	// bookreadingprogressDescID is the schema descriptor for id field.
	bookreadingprogressDescID := bookreadingprogressFields[0].Descriptor()
	// bookreadingprogress.DefaultID holds the default value on creation for the id field.
	bookreadingprogress.DefaultID = bookreadingprogressDescID.Default.(func() uuid.UUID)
	bookreviewFields := schema.BookReview{}.Fields()
	_ = bookreviewFields
	// bookreviewDescAction is the schema descriptor for action field.
	bookreviewDescAction := bookreviewFields[3].Descriptor()
	// bookreview.ActionValidator is a validator for the "action" field. It is called by the builders before save.
	bookreview.ActionValidator = func() func(string) error {
		validators := bookreviewDescAction.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(action string) error {
			for _, fn := range fns {
				if err := fn(action); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// bookreviewDescStatusFrom is the schema descriptor for status_from field.
	bookreviewDescStatusFrom := bookreviewFields[4].Descriptor()
	// bookreview.StatusFromValidator is a validator for the "status_from" field. It is called by the builders before save.
	bookreview.StatusFromValidator = bookreviewDescStatusFrom.Validators[0].(func(string) error)
	// bookreviewDescStatusTo is the schema descriptor for status_to field.
	bookreviewDescStatusTo := bookreviewFields[5].Descriptor()
	// bookreview.StatusToValidator is a validator for the "status_to" field. It is called by the builders before save.
	bookreview.StatusToValidator = bookreviewDescStatusTo.Validators[0].(func(string) error)
	// bookreviewDescReason is the schema descriptor for reason field.
	bookreviewDescReason := bookreviewFields[6].Descriptor()
	// bookreview.DefaultReason holds the default value on creation for the reason field.
	bookreview.DefaultReason = bookreviewDescReason.Default.(string)
	// bookreviewDescCreatedAt is the schema descriptor for created_at field.
	bookreviewDescCreatedAt := bookreviewFields[7].Descriptor()
	// bookreview.DefaultCreatedAt holds the default value on creation for the created_at field.
	bookreview.DefaultCreatedAt = bookreviewDescCreatedAt.Default.(func() time.Time)
	// bookreviewDescID is the schema descriptor for id field.
	bookreviewDescID := bookreviewFields[0].Descriptor()
	// bookreview.DefaultID holds the default value on creation for the id field.
	bookreview.DefaultID = bookreviewDescID.Default.(func() uuid.UUID)
	booksearchindexFields := schema.BookSearchIndex{}.Fields()
	_ = booksearchindexFields
	// booksearchindexDescID is the schema descriptor for id field.
	booksearchindexDescID := booksearchindexFields[0].Descriptor()
	// booksearchindex.DefaultID holds the default value on creation for the id field.
	booksearchindex.DefaultID = booksearchindexDescID.Default.(func() uuid.UUID)
	dimensionFields := schema.Dimension{}.Fields()
	_ = dimensionFields
	// dimensionDescName is the schema descriptor for name field.
	dimensionDescName := dimensionFields[1].Descriptor()
	// dimension.NameValidator is a validator for the "name" field. It is called by the builders before save.
	dimension.NameValidator = func() func(string) error {
		validators := dimensionDescName.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(name string) error {
			for _, fn := range fns {
				if err := fn(name); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// dimensionDescSlug is the schema descriptor for slug field.
	dimensionDescSlug := dimensionFields[2].Descriptor()
	// dimension.SlugValidator is a validator for the "slug" field. It is called by the builders before save.
	dimension.SlugValidator = func() func(string) error {
		validators := dimensionDescSlug.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
			validators[2].(func(string) error),
		}
		return func(slug string) error {
			for _, fn := range fns {
				if err := fn(slug); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// dimensionDescDescription is the schema descriptor for description field.
	dimensionDescDescription := dimensionFields[3].Descriptor()
	// dimension.DescriptionValidator is a validator for the "description" field. It is called by the builders before save.
	dimension.DescriptionValidator = dimensionDescDescription.Validators[0].(func(string) error)
	// dimensionDescSortOrder is the schema descriptor for sort_order field.
	dimensionDescSortOrder := dimensionFields[4].Descriptor()
	// dimension.DefaultSortOrder holds the default value on creation for the sort_order field.
	dimension.DefaultSortOrder = dimensionDescSortOrder.Default.(int)
	// dimensionDescCreatedAt is the schema descriptor for created_at field.
	dimensionDescCreatedAt := dimensionFields[5].Descriptor()
	// dimension.DefaultCreatedAt holds the default value on creation for the created_at field.
	dimension.DefaultCreatedAt = dimensionDescCreatedAt.Default.(func() time.Time)
	// dimensionDescUpdatedAt is the schema descriptor for updated_at field.
	dimensionDescUpdatedAt := dimensionFields[6].Descriptor()
	// dimension.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	dimension.DefaultUpdatedAt = dimensionDescUpdatedAt.Default.(func() time.Time)
	// dimension.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	dimension.UpdateDefaultUpdatedAt = dimensionDescUpdatedAt.UpdateDefault.(func() time.Time)
	// dimensionDescID is the schema descriptor for id field.
	dimensionDescID := dimensionFields[0].Descriptor()
	// dimension.DefaultID holds the default value on creation for the id field.
	dimension.DefaultID = dimensionDescID.Default.(func() uuid.UUID)
	userFields := schema.User{}.Fields()
	_ = userFields
	// userDescUsername is the schema descriptor for username field.
	userDescUsername := userFields[1].Descriptor()
	// user.UsernameValidator is a validator for the "username" field. It is called by the builders before save.
	user.UsernameValidator = func() func(string) error {
		validators := userDescUsername.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
			validators[2].(func(string) error),
		}
		return func(username string) error {
			for _, fn := range fns {
				if err := fn(username); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// userDescEmail is the schema descriptor for email field.
	userDescEmail := userFields[2].Descriptor()
	// user.EmailValidator is a validator for the "email" field. It is called by the builders before save.
	user.EmailValidator = userDescEmail.Validators[0].(func(string) error)
	// userDescPasswordHash is the schema descriptor for password_hash field.
	userDescPasswordHash := userFields[3].Descriptor()
	// user.PasswordHashValidator is a validator for the "password_hash" field. It is called by the builders before save.
	user.PasswordHashValidator = userDescPasswordHash.Validators[0].(func(string) error)
	// userDescCreatedAt is the schema descriptor for created_at field.
	userDescCreatedAt := userFields[5].Descriptor()
	// user.DefaultCreatedAt holds the default value on creation for the created_at field.
	user.DefaultCreatedAt = userDescCreatedAt.Default.(func() time.Time)
	// userDescUpdatedAt is the schema descriptor for updated_at field.
	userDescUpdatedAt := userFields[6].Descriptor()
	// user.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	user.DefaultUpdatedAt = userDescUpdatedAt.Default.(func() time.Time)
	// user.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	user.UpdateDefaultUpdatedAt = userDescUpdatedAt.UpdateDefault.(func() time.Time)
	// userDescID is the schema descriptor for id field.
	userDescID := userFields[0].Descriptor()
	// user.DefaultID holds the default value on creation for the id field.
	user.DefaultID = userDescID.Default.(func() uuid.UUID)
}
